// <auto-generated/>
// Locale: cs

namespace ExampleTwo.Localizations;

public static class L_cs {

    /// <returns>Arb.NET Příklad Dva</returns>
    public static string AppTitle
        => "Arb.NET Příklad Dva";

    /// <returns>Dospělý</returns>
    public static string MyEnumOneGrownUp
        => "Dospělý";

    /// <returns>Senior</returns>
    public static string MyEnumOneOld
        => "Senior";

    /// <returns>Junior</returns>
    public static string MyEnumOneYoung
        => "Junior";
}
