// <auto-generated/>
// Locale: en

namespace ExampleTwo.Localizations;

public static class L_en {

    /// <returns>Arb.NET Example Two</returns>
    public static string AppTitle
        => "Arb.NET Example Two";

    /// <summary>Age group of the person</summary>
    /// <returns>Adult</returns>
    public static string MyEnumOneGrownUp
        => "Adult";

    /// <summary>Age group of the person</summary>
    /// <returns>Senior</returns>
    public static string MyEnumOneOld
        => "Senior";

    /// <summary>Age group of the person</summary>
    /// <returns>Juvenile</returns>
    public static string MyEnumOneYoung
        => "Juvenile";
}
