// <auto-generated/>
// Available locales: en, cs
#nullable enable

namespace ExampleTwo.Localizations;

public partial class L : global::Arb.NET.IArbLocale {
    private readonly System.Globalization.CultureInfo _culture;

    public L(System.Globalization.CultureInfo culture) {
        _culture = culture;
    }

    private static string ResolveLocale(System.Globalization.CultureInfo culture) {
        var name = culture.Name.Replace("-", "_");
        return name switch {
            "en" => "en",
            "cs" => "cs",
            _ => TryParent(culture)
        };
    }

    private static string TryParent(System.Globalization.CultureInfo culture) {
        if (!culture.IsNeutralCulture) {
            var parent = culture.Parent;
            if (!string.IsNullOrEmpty(parent.Name))
                return ResolveLocale(parent);
        }
        throw new System.NotSupportedException(
            $"No localization found for '{culture.Name}'. Available: en, cs");
    }

    /// <summary>
    /// <list type="table">
    /// <listheader><term>Locale</term><description>Value</description></listheader>
    /// <item><term>en</term><description>Arb.NET Example Two</description></item>
    /// <item><term>cs</term><description>Arb.NET Příklad Dva</description></item>
    /// </list>
    /// </summary>
    public string AppTitle => ResolveLocale(_culture) switch {
        "en" => L_en.AppTitle,
        "cs" => L_cs.AppTitle,
        _ => throw new System.NotSupportedException(
            $"No localization found for '{_culture.Name}'. Available: en, cs")
    };

    /// <summary>
    /// Age group of the person
    /// <list type="table">
    /// <listheader><term>Locale</term><description>Value</description></listheader>
    /// <item><term>en</term><description>Adult</description></item>
    /// <item><term>cs</term><description>Dospělý</description></item>
    /// </list>
    /// </summary>
    public string MyEnumOneGrownUp => ResolveLocale(_culture) switch {
        "en" => L_en.MyEnumOneGrownUp,
        "cs" => L_cs.MyEnumOneGrownUp,
        _ => throw new System.NotSupportedException(
            $"No localization found for '{_culture.Name}'. Available: en, cs")
    };

    /// <summary>
    /// Age group of the person
    /// <list type="table">
    /// <listheader><term>Locale</term><description>Value</description></listheader>
    /// <item><term>en</term><description>Senior</description></item>
    /// <item><term>cs</term><description>Senior</description></item>
    /// </list>
    /// </summary>
    public string MyEnumOneOld => ResolveLocale(_culture) switch {
        "en" => L_en.MyEnumOneOld,
        "cs" => L_cs.MyEnumOneOld,
        _ => throw new System.NotSupportedException(
            $"No localization found for '{_culture.Name}'. Available: en, cs")
    };

    /// <summary>
    /// Age group of the person
    /// <list type="table">
    /// <listheader><term>Locale</term><description>Value</description></listheader>
    /// <item><term>en</term><description>Juvenile</description></item>
    /// <item><term>cs</term><description>Junior</description></item>
    /// </list>
    /// </summary>
    public string MyEnumOneYoung => ResolveLocale(_culture) switch {
        "en" => L_en.MyEnumOneYoung,
        "cs" => L_cs.MyEnumOneYoung,
        _ => throw new System.NotSupportedException(
            $"No localization found for '{_culture.Name}'. Available: en, cs")
    };

    /// <summary>Returns the localized string for the given raw ARB key, or null if not found.</summary>
    public string? this[string? key] => key switch {
        "appTitle" => AppTitle,
        "AppTitle" => AppTitle,
        "myEnumOneGrownUp" => MyEnumOneGrownUp,
        "MyEnumOneGrownUp" => MyEnumOneGrownUp,
        "myEnumOneOld" => MyEnumOneOld,
        "MyEnumOneOld" => MyEnumOneOld,
        "myEnumOneYoung" => MyEnumOneYoung,
        "MyEnumOneYoung" => MyEnumOneYoung,
        _ => null
    };

    /// <summary>Returns the localized display name for a <see cref="global::Arb.NET.ExampleTwo.MyEnumOne"/> value.</summary>
    public string Localize(global::Arb.NET.ExampleTwo.MyEnumOne value) {
        return value switch {
            global::Arb.NET.ExampleTwo.MyEnumOne.Young => MyEnumOneYoung,
            global::Arb.NET.ExampleTwo.MyEnumOne.GrownUp => MyEnumOneGrownUp,
            global::Arb.NET.ExampleTwo.MyEnumOne.Old => MyEnumOneOld,
            _ => value.ToString()
        };
    }
}
