//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:9</p>
  /// </summary>
  public class ArbModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<string, List<ArbLocaleData>> GetArbData => _GetArbData;
    [NotNull] public IRdEndpoint<ArbEntryUpdate, bool> SaveArbEntry => _SaveArbEntry;
    [NotNull] public IRdEndpoint<ArbKeyRename, bool> RenameArbKey => _RenameArbKey;
    [NotNull] public IRdEndpoint<ArbNewKey, bool> AddArbKey => _AddArbKey;
    [NotNull] public IRdEndpoint<ArbRemoveKey, bool> RemoveArbKey => _RemoveArbKey;
    [NotNull] public IRdEndpoint<ArbNewLocale, bool> AddArbLocale => _AddArbLocale;
    [NotNull] public IRdEndpoint<ArbTranslateRequest, ArbTranslateResponse> TranslateArbEntries => _TranslateArbEntries;
    [NotNull] public IRdEndpoint<ArbCsvPreviewRequest, ArbCsvPreviewResponse> PreviewArbCsvImport => _PreviewArbCsvImport;
    [NotNull] public IRdEndpoint<ArbCsvImportRequest, ArbCsvImportResponse> ApplyArbCsvImport => _ApplyArbCsvImport;
    [NotNull] public IRdEndpoint<string, ArbCsvExportResponse> ExportArbCsv => _ExportArbCsv;
    [NotNull] public IRdEndpoint<string, List<ArbKeyInfo>> GetArbKeys => _GetArbKeys;
    [NotNull] public ISignal<ArbOpenEditor> OpenArbEditor => _OpenArbEditor;
    [NotNull] public ISignal<string> ArbKeysChanged => _ArbKeysChanged;
    
    //private fields
    [NotNull] private readonly RdCall<string, List<ArbLocaleData>> _GetArbData;
    [NotNull] private readonly RdCall<ArbEntryUpdate, bool> _SaveArbEntry;
    [NotNull] private readonly RdCall<ArbKeyRename, bool> _RenameArbKey;
    [NotNull] private readonly RdCall<ArbNewKey, bool> _AddArbKey;
    [NotNull] private readonly RdCall<ArbRemoveKey, bool> _RemoveArbKey;
    [NotNull] private readonly RdCall<ArbNewLocale, bool> _AddArbLocale;
    [NotNull] private readonly RdCall<ArbTranslateRequest, ArbTranslateResponse> _TranslateArbEntries;
    [NotNull] private readonly RdCall<ArbCsvPreviewRequest, ArbCsvPreviewResponse> _PreviewArbCsvImport;
    [NotNull] private readonly RdCall<ArbCsvImportRequest, ArbCsvImportResponse> _ApplyArbCsvImport;
    [NotNull] private readonly RdCall<string, ArbCsvExportResponse> _ExportArbCsv;
    [NotNull] private readonly RdCall<string, List<ArbKeyInfo>> _GetArbKeys;
    [NotNull] private readonly RdSignal<ArbOpenEditor> _OpenArbEditor;
    [NotNull] private readonly RdSignal<string> _ArbKeysChanged;
    
    //primary constructor
    private ArbModel(
      [NotNull] RdCall<string, List<ArbLocaleData>> getArbData,
      [NotNull] RdCall<ArbEntryUpdate, bool> saveArbEntry,
      [NotNull] RdCall<ArbKeyRename, bool> renameArbKey,
      [NotNull] RdCall<ArbNewKey, bool> addArbKey,
      [NotNull] RdCall<ArbRemoveKey, bool> removeArbKey,
      [NotNull] RdCall<ArbNewLocale, bool> addArbLocale,
      [NotNull] RdCall<ArbTranslateRequest, ArbTranslateResponse> translateArbEntries,
      [NotNull] RdCall<ArbCsvPreviewRequest, ArbCsvPreviewResponse> previewArbCsvImport,
      [NotNull] RdCall<ArbCsvImportRequest, ArbCsvImportResponse> applyArbCsvImport,
      [NotNull] RdCall<string, ArbCsvExportResponse> exportArbCsv,
      [NotNull] RdCall<string, List<ArbKeyInfo>> getArbKeys,
      [NotNull] RdSignal<ArbOpenEditor> openArbEditor,
      [NotNull] RdSignal<string> arbKeysChanged
    )
    {
      if (getArbData == null) throw new ArgumentNullException("getArbData");
      if (saveArbEntry == null) throw new ArgumentNullException("saveArbEntry");
      if (renameArbKey == null) throw new ArgumentNullException("renameArbKey");
      if (addArbKey == null) throw new ArgumentNullException("addArbKey");
      if (removeArbKey == null) throw new ArgumentNullException("removeArbKey");
      if (addArbLocale == null) throw new ArgumentNullException("addArbLocale");
      if (translateArbEntries == null) throw new ArgumentNullException("translateArbEntries");
      if (previewArbCsvImport == null) throw new ArgumentNullException("previewArbCsvImport");
      if (applyArbCsvImport == null) throw new ArgumentNullException("applyArbCsvImport");
      if (exportArbCsv == null) throw new ArgumentNullException("exportArbCsv");
      if (getArbKeys == null) throw new ArgumentNullException("getArbKeys");
      if (openArbEditor == null) throw new ArgumentNullException("openArbEditor");
      if (arbKeysChanged == null) throw new ArgumentNullException("arbKeysChanged");
      
      _GetArbData = getArbData;
      _SaveArbEntry = saveArbEntry;
      _RenameArbKey = renameArbKey;
      _AddArbKey = addArbKey;
      _RemoveArbKey = removeArbKey;
      _AddArbLocale = addArbLocale;
      _TranslateArbEntries = translateArbEntries;
      _PreviewArbCsvImport = previewArbCsvImport;
      _ApplyArbCsvImport = applyArbCsvImport;
      _ExportArbCsv = exportArbCsv;
      _GetArbKeys = getArbKeys;
      _OpenArbEditor = openArbEditor;
      _ArbKeysChanged = arbKeysChanged;
      BindableChildren.Add(new KeyValuePair<string, object>("getArbData", _GetArbData));
      BindableChildren.Add(new KeyValuePair<string, object>("saveArbEntry", _SaveArbEntry));
      BindableChildren.Add(new KeyValuePair<string, object>("renameArbKey", _RenameArbKey));
      BindableChildren.Add(new KeyValuePair<string, object>("addArbKey", _AddArbKey));
      BindableChildren.Add(new KeyValuePair<string, object>("removeArbKey", _RemoveArbKey));
      BindableChildren.Add(new KeyValuePair<string, object>("addArbLocale", _AddArbLocale));
      BindableChildren.Add(new KeyValuePair<string, object>("translateArbEntries", _TranslateArbEntries));
      BindableChildren.Add(new KeyValuePair<string, object>("previewArbCsvImport", _PreviewArbCsvImport));
      BindableChildren.Add(new KeyValuePair<string, object>("applyArbCsvImport", _ApplyArbCsvImport));
      BindableChildren.Add(new KeyValuePair<string, object>("exportArbCsv", _ExportArbCsv));
      BindableChildren.Add(new KeyValuePair<string, object>("getArbKeys", _GetArbKeys));
      BindableChildren.Add(new KeyValuePair<string, object>("openArbEditor", _OpenArbEditor));
      BindableChildren.Add(new KeyValuePair<string, object>("arbKeysChanged", _ArbKeysChanged));
    }
    //secondary constructor
    internal ArbModel (
    ) : this (
      new RdCall<string, List<ArbLocaleData>>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString, ReadArbLocaleDataList, WriteArbLocaleDataList),
      new RdCall<ArbEntryUpdate, bool>(ArbEntryUpdate.Read, ArbEntryUpdate.Write, JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdCall<ArbKeyRename, bool>(ArbKeyRename.Read, ArbKeyRename.Write, JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdCall<ArbNewKey, bool>(ArbNewKey.Read, ArbNewKey.Write, JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdCall<ArbRemoveKey, bool>(ArbRemoveKey.Read, ArbRemoveKey.Write, JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdCall<ArbNewLocale, bool>(ArbNewLocale.Read, ArbNewLocale.Write, JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdCall<ArbTranslateRequest, ArbTranslateResponse>(ArbTranslateRequest.Read, ArbTranslateRequest.Write, ArbTranslateResponse.Read, ArbTranslateResponse.Write),
      new RdCall<ArbCsvPreviewRequest, ArbCsvPreviewResponse>(ArbCsvPreviewRequest.Read, ArbCsvPreviewRequest.Write, ArbCsvPreviewResponse.Read, ArbCsvPreviewResponse.Write),
      new RdCall<ArbCsvImportRequest, ArbCsvImportResponse>(ArbCsvImportRequest.Read, ArbCsvImportRequest.Write, ArbCsvImportResponse.Read, ArbCsvImportResponse.Write),
      new RdCall<string, ArbCsvExportResponse>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString, ArbCsvExportResponse.Read, ArbCsvExportResponse.Write),
      new RdCall<string, List<ArbKeyInfo>>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString, ReadArbKeyInfoList, WriteArbKeyInfoList),
      new RdSignal<ArbOpenEditor>(ArbOpenEditor.Read, ArbOpenEditor.Write),
      new RdSignal<string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString)
    ) {}
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<List<ArbLocaleData>> ReadArbLocaleDataList = ArbLocaleData.Read.List();
    public static CtxReadDelegate<List<ArbKeyInfo>> ReadArbKeyInfoList = ArbKeyInfo.Read.List();
    
    public static  CtxWriteDelegate<List<ArbLocaleData>> WriteArbLocaleDataList = ArbLocaleData.Write.List();
    public static  CtxWriteDelegate<List<ArbKeyInfo>> WriteArbKeyInfoList = ArbKeyInfo.Write.List();
    
    protected override long SerializationHash => -8433798428104670542L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("ArbModel (");
      using (printer.IndentCookie()) {
        printer.Print("getArbData = "); _GetArbData.PrintEx(printer); printer.Println();
        printer.Print("saveArbEntry = "); _SaveArbEntry.PrintEx(printer); printer.Println();
        printer.Print("renameArbKey = "); _RenameArbKey.PrintEx(printer); printer.Println();
        printer.Print("addArbKey = "); _AddArbKey.PrintEx(printer); printer.Println();
        printer.Print("removeArbKey = "); _RemoveArbKey.PrintEx(printer); printer.Println();
        printer.Print("addArbLocale = "); _AddArbLocale.PrintEx(printer); printer.Println();
        printer.Print("translateArbEntries = "); _TranslateArbEntries.PrintEx(printer); printer.Println();
        printer.Print("previewArbCsvImport = "); _PreviewArbCsvImport.PrintEx(printer); printer.Println();
        printer.Print("applyArbCsvImport = "); _ApplyArbCsvImport.PrintEx(printer); printer.Println();
        printer.Print("exportArbCsv = "); _ExportArbCsv.PrintEx(printer); printer.Println();
        printer.Print("getArbKeys = "); _GetArbKeys.PrintEx(printer); printer.Println();
        printer.Print("openArbEditor = "); _OpenArbEditor.PrintEx(printer); printer.Println();
        printer.Print("arbKeysChanged = "); _ArbKeysChanged.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionArbModelEx
   {
    public static ArbModel GetArbModel(this Solution solution)
    {
      return solution.GetOrCreateExtension("arbModel", () => new ArbModel());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:128</p>
  /// </summary>
  public sealed class ArbCsvExportResponse : IPrintable, IEquatable<ArbCsvExportResponse>
  {
    //fields
    //public fields
    public bool Success {get; private set;}
    [CanBeNull] public string ErrorMessage {get; private set;}
    [NotNull] public string CsvContent {get; private set;}
    
    //private fields
    //primary constructor
    public ArbCsvExportResponse(
      bool success,
      [CanBeNull] string errorMessage,
      [NotNull] string csvContent
    )
    {
      if (csvContent == null) throw new ArgumentNullException("csvContent");
      
      Success = success;
      ErrorMessage = errorMessage;
      CsvContent = csvContent;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out bool success, [CanBeNull] out string errorMessage, [NotNull] out string csvContent)
    {
      success = Success;
      errorMessage = ErrorMessage;
      csvContent = CsvContent;
    }
    //statics
    
    public static CtxReadDelegate<ArbCsvExportResponse> Read = (ctx, reader) => 
    {
      var success = reader.ReadBool();
      var errorMessage = ReadStringNullable(ctx, reader);
      var csvContent = reader.ReadString();
      var _result = new ArbCsvExportResponse(success, errorMessage, csvContent);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    
    public static CtxWriteDelegate<ArbCsvExportResponse> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Success);
      WriteStringNullable(ctx, writer, value.ErrorMessage);
      writer.Write(value.CsvContent);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbCsvExportResponse) obj);
    }
    public bool Equals(ArbCsvExportResponse other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Success == other.Success && Equals(ErrorMessage, other.ErrorMessage) && CsvContent == other.CsvContent;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Success.GetHashCode();
        hash = hash * 31 + (ErrorMessage != null ? ErrorMessage.GetHashCode() : 0);
        hash = hash * 31 + CsvContent.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbCsvExportResponse (");
      using (printer.IndentCookie()) {
        printer.Print("success = "); Success.PrintEx(printer); printer.Println();
        printer.Print("errorMessage = "); ErrorMessage.PrintEx(printer); printer.Println();
        printer.Print("csvContent = "); CsvContent.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:113</p>
  /// </summary>
  public sealed class ArbCsvImportRequest : IPrintable, IEquatable<ArbCsvImportRequest>
  {
    //fields
    //public fields
    [NotNull] public string Directory {get; private set;}
    [NotNull] public string CsvContent {get; private set;}
    [NotNull] public List<string> Mappings {get; private set;}
    [NotNull] public string Mode {get; private set;}
    
    //private fields
    //primary constructor
    public ArbCsvImportRequest(
      [NotNull] string directory,
      [NotNull] string csvContent,
      [NotNull] List<string> mappings,
      [NotNull] string mode
    )
    {
      if (directory == null) throw new ArgumentNullException("directory");
      if (csvContent == null) throw new ArgumentNullException("csvContent");
      if (mappings == null) throw new ArgumentNullException("mappings");
      if (mode == null) throw new ArgumentNullException("mode");
      
      Directory = directory;
      CsvContent = csvContent;
      Mappings = mappings;
      Mode = mode;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string directory, [NotNull] out string csvContent, [NotNull] out List<string> mappings, [NotNull] out string mode)
    {
      directory = Directory;
      csvContent = CsvContent;
      mappings = Mappings;
      mode = Mode;
    }
    //statics
    
    public static CtxReadDelegate<ArbCsvImportRequest> Read = (ctx, reader) => 
    {
      var directory = reader.ReadString();
      var csvContent = reader.ReadString();
      var mappings = ReadStringList(ctx, reader);
      var mode = reader.ReadString();
      var _result = new ArbCsvImportRequest(directory, csvContent, mappings, mode);
      return _result;
    };
    public static CtxReadDelegate<List<string>> ReadStringList = JetBrains.Rd.Impl.Serializers.ReadString.List();
    
    public static CtxWriteDelegate<ArbCsvImportRequest> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Directory);
      writer.Write(value.CsvContent);
      WriteStringList(ctx, writer, value.Mappings);
      writer.Write(value.Mode);
    };
    public static  CtxWriteDelegate<List<string>> WriteStringList = JetBrains.Rd.Impl.Serializers.WriteString.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbCsvImportRequest) obj);
    }
    public bool Equals(ArbCsvImportRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Directory == other.Directory && CsvContent == other.CsvContent && Mappings.SequenceEqual(other.Mappings) && Mode == other.Mode;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Directory.GetHashCode();
        hash = hash * 31 + CsvContent.GetHashCode();
        hash = hash * 31 + Mappings.ContentHashCode();
        hash = hash * 31 + Mode.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbCsvImportRequest (");
      using (printer.IndentCookie()) {
        printer.Print("directory = "); Directory.PrintEx(printer); printer.Println();
        printer.Print("csvContent = "); CsvContent.PrintEx(printer); printer.Println();
        printer.Print("mappings = "); Mappings.PrintEx(printer); printer.Println();
        printer.Print("mode = "); Mode.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:120</p>
  /// </summary>
  public sealed class ArbCsvImportResponse : IPrintable, IEquatable<ArbCsvImportResponse>
  {
    //fields
    //public fields
    public bool Success {get; private set;}
    [CanBeNull] public string ErrorMessage {get; private set;}
    public int ImportedKeyCount {get; private set;}
    public int AffectedLocaleCount {get; private set;}
    public int CreatedLocaleCount {get; private set;}
    
    //private fields
    //primary constructor
    public ArbCsvImportResponse(
      bool success,
      [CanBeNull] string errorMessage,
      int importedKeyCount,
      int affectedLocaleCount,
      int createdLocaleCount
    )
    {
      Success = success;
      ErrorMessage = errorMessage;
      ImportedKeyCount = importedKeyCount;
      AffectedLocaleCount = affectedLocaleCount;
      CreatedLocaleCount = createdLocaleCount;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out bool success, [CanBeNull] out string errorMessage, out int importedKeyCount, out int affectedLocaleCount, out int createdLocaleCount)
    {
      success = Success;
      errorMessage = ErrorMessage;
      importedKeyCount = ImportedKeyCount;
      affectedLocaleCount = AffectedLocaleCount;
      createdLocaleCount = CreatedLocaleCount;
    }
    //statics
    
    public static CtxReadDelegate<ArbCsvImportResponse> Read = (ctx, reader) => 
    {
      var success = reader.ReadBool();
      var errorMessage = ReadStringNullable(ctx, reader);
      var importedKeyCount = reader.ReadInt();
      var affectedLocaleCount = reader.ReadInt();
      var createdLocaleCount = reader.ReadInt();
      var _result = new ArbCsvImportResponse(success, errorMessage, importedKeyCount, affectedLocaleCount, createdLocaleCount);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    
    public static CtxWriteDelegate<ArbCsvImportResponse> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Success);
      WriteStringNullable(ctx, writer, value.ErrorMessage);
      writer.Write(value.ImportedKeyCount);
      writer.Write(value.AffectedLocaleCount);
      writer.Write(value.CreatedLocaleCount);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbCsvImportResponse) obj);
    }
    public bool Equals(ArbCsvImportResponse other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Success == other.Success && Equals(ErrorMessage, other.ErrorMessage) && ImportedKeyCount == other.ImportedKeyCount && AffectedLocaleCount == other.AffectedLocaleCount && CreatedLocaleCount == other.CreatedLocaleCount;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Success.GetHashCode();
        hash = hash * 31 + (ErrorMessage != null ? ErrorMessage.GetHashCode() : 0);
        hash = hash * 31 + ImportedKeyCount.GetHashCode();
        hash = hash * 31 + AffectedLocaleCount.GetHashCode();
        hash = hash * 31 + CreatedLocaleCount.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbCsvImportResponse (");
      using (printer.IndentCookie()) {
        printer.Print("success = "); Success.PrintEx(printer); printer.Println();
        printer.Print("errorMessage = "); ErrorMessage.PrintEx(printer); printer.Println();
        printer.Print("importedKeyCount = "); ImportedKeyCount.PrintEx(printer); printer.Println();
        printer.Print("affectedLocaleCount = "); AffectedLocaleCount.PrintEx(printer); printer.Println();
        printer.Print("createdLocaleCount = "); CreatedLocaleCount.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:94</p>
  /// </summary>
  public sealed class ArbCsvPreviewRequest : IPrintable, IEquatable<ArbCsvPreviewRequest>
  {
    //fields
    //public fields
    [NotNull] public string Directory {get; private set;}
    [NotNull] public string CsvContent {get; private set;}
    
    //private fields
    //primary constructor
    public ArbCsvPreviewRequest(
      [NotNull] string directory,
      [NotNull] string csvContent
    )
    {
      if (directory == null) throw new ArgumentNullException("directory");
      if (csvContent == null) throw new ArgumentNullException("csvContent");
      
      Directory = directory;
      CsvContent = csvContent;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string directory, [NotNull] out string csvContent)
    {
      directory = Directory;
      csvContent = CsvContent;
    }
    //statics
    
    public static CtxReadDelegate<ArbCsvPreviewRequest> Read = (ctx, reader) => 
    {
      var directory = reader.ReadString();
      var csvContent = reader.ReadString();
      var _result = new ArbCsvPreviewRequest(directory, csvContent);
      return _result;
    };
    
    public static CtxWriteDelegate<ArbCsvPreviewRequest> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Directory);
      writer.Write(value.CsvContent);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbCsvPreviewRequest) obj);
    }
    public bool Equals(ArbCsvPreviewRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Directory == other.Directory && CsvContent == other.CsvContent;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Directory.GetHashCode();
        hash = hash * 31 + CsvContent.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbCsvPreviewRequest (");
      using (printer.IndentCookie()) {
        printer.Print("directory = "); Directory.PrintEx(printer); printer.Println();
        printer.Print("csvContent = "); CsvContent.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:103</p>
  /// </summary>
  public sealed class ArbCsvPreviewResponse : IPrintable, IEquatable<ArbCsvPreviewResponse>
  {
    //fields
    //public fields
    public bool Success {get; private set;}
    [CanBeNull] public string ErrorMessage {get; private set;}
    [NotNull] public List<string> Headers {get; private set;}
    [NotNull] public List<ArbCsvRow> Rows {get; private set;}
    [NotNull] public List<string> SuggestedMappings {get; private set;}
    [NotNull] public List<string> AvailableLocaleMappings {get; private set;}
    [CanBeNull] public string DefaultLocale {get; private set;}
    
    //private fields
    //primary constructor
    public ArbCsvPreviewResponse(
      bool success,
      [CanBeNull] string errorMessage,
      [NotNull] List<string> headers,
      [NotNull] List<ArbCsvRow> rows,
      [NotNull] List<string> suggestedMappings,
      [NotNull] List<string> availableLocaleMappings,
      [CanBeNull] string defaultLocale
    )
    {
      if (headers == null) throw new ArgumentNullException("headers");
      if (rows == null) throw new ArgumentNullException("rows");
      if (suggestedMappings == null) throw new ArgumentNullException("suggestedMappings");
      if (availableLocaleMappings == null) throw new ArgumentNullException("availableLocaleMappings");
      
      Success = success;
      ErrorMessage = errorMessage;
      Headers = headers;
      Rows = rows;
      SuggestedMappings = suggestedMappings;
      AvailableLocaleMappings = availableLocaleMappings;
      DefaultLocale = defaultLocale;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out bool success, [CanBeNull] out string errorMessage, [NotNull] out List<string> headers, [NotNull] out List<ArbCsvRow> rows, [NotNull] out List<string> suggestedMappings, [NotNull] out List<string> availableLocaleMappings, [CanBeNull] out string defaultLocale)
    {
      success = Success;
      errorMessage = ErrorMessage;
      headers = Headers;
      rows = Rows;
      suggestedMappings = SuggestedMappings;
      availableLocaleMappings = AvailableLocaleMappings;
      defaultLocale = DefaultLocale;
    }
    //statics
    
    public static CtxReadDelegate<ArbCsvPreviewResponse> Read = (ctx, reader) => 
    {
      var success = reader.ReadBool();
      var errorMessage = ReadStringNullable(ctx, reader);
      var headers = ReadStringList(ctx, reader);
      var rows = ReadArbCsvRowList(ctx, reader);
      var suggestedMappings = ReadStringList(ctx, reader);
      var availableLocaleMappings = ReadStringList(ctx, reader);
      var defaultLocale = ReadStringNullable(ctx, reader);
      var _result = new ArbCsvPreviewResponse(success, errorMessage, headers, rows, suggestedMappings, availableLocaleMappings, defaultLocale);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    public static CtxReadDelegate<List<string>> ReadStringList = JetBrains.Rd.Impl.Serializers.ReadString.List();
    public static CtxReadDelegate<List<ArbCsvRow>> ReadArbCsvRowList = ArbCsvRow.Read.List();
    
    public static CtxWriteDelegate<ArbCsvPreviewResponse> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Success);
      WriteStringNullable(ctx, writer, value.ErrorMessage);
      WriteStringList(ctx, writer, value.Headers);
      WriteArbCsvRowList(ctx, writer, value.Rows);
      WriteStringList(ctx, writer, value.SuggestedMappings);
      WriteStringList(ctx, writer, value.AvailableLocaleMappings);
      WriteStringNullable(ctx, writer, value.DefaultLocale);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    public static  CtxWriteDelegate<List<string>> WriteStringList = JetBrains.Rd.Impl.Serializers.WriteString.List();
    public static  CtxWriteDelegate<List<ArbCsvRow>> WriteArbCsvRowList = ArbCsvRow.Write.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbCsvPreviewResponse) obj);
    }
    public bool Equals(ArbCsvPreviewResponse other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Success == other.Success && Equals(ErrorMessage, other.ErrorMessage) && Headers.SequenceEqual(other.Headers) && Rows.SequenceEqual(other.Rows) && SuggestedMappings.SequenceEqual(other.SuggestedMappings) && AvailableLocaleMappings.SequenceEqual(other.AvailableLocaleMappings) && Equals(DefaultLocale, other.DefaultLocale);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Success.GetHashCode();
        hash = hash * 31 + (ErrorMessage != null ? ErrorMessage.GetHashCode() : 0);
        hash = hash * 31 + Headers.ContentHashCode();
        hash = hash * 31 + Rows.ContentHashCode();
        hash = hash * 31 + SuggestedMappings.ContentHashCode();
        hash = hash * 31 + AvailableLocaleMappings.ContentHashCode();
        hash = hash * 31 + (DefaultLocale != null ? DefaultLocale.GetHashCode() : 0);
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbCsvPreviewResponse (");
      using (printer.IndentCookie()) {
        printer.Print("success = "); Success.PrintEx(printer); printer.Println();
        printer.Print("errorMessage = "); ErrorMessage.PrintEx(printer); printer.Println();
        printer.Print("headers = "); Headers.PrintEx(printer); printer.Println();
        printer.Print("rows = "); Rows.PrintEx(printer); printer.Println();
        printer.Print("suggestedMappings = "); SuggestedMappings.PrintEx(printer); printer.Println();
        printer.Print("availableLocaleMappings = "); AvailableLocaleMappings.PrintEx(printer); printer.Println();
        printer.Print("defaultLocale = "); DefaultLocale.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:99</p>
  /// </summary>
  public sealed class ArbCsvRow : IPrintable, IEquatable<ArbCsvRow>
  {
    //fields
    //public fields
    [NotNull] public List<string> Cells {get; private set;}
    
    //private fields
    //primary constructor
    public ArbCsvRow(
      [NotNull] List<string> cells
    )
    {
      if (cells == null) throw new ArgumentNullException("cells");
      
      Cells = cells;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out List<string> cells)
    {
      cells = Cells;
    }
    //statics
    
    public static CtxReadDelegate<ArbCsvRow> Read = (ctx, reader) => 
    {
      var cells = ReadStringList(ctx, reader);
      var _result = new ArbCsvRow(cells);
      return _result;
    };
    public static CtxReadDelegate<List<string>> ReadStringList = JetBrains.Rd.Impl.Serializers.ReadString.List();
    
    public static CtxWriteDelegate<ArbCsvRow> Write = (ctx, writer, value) => 
    {
      WriteStringList(ctx, writer, value.Cells);
    };
    public static  CtxWriteDelegate<List<string>> WriteStringList = JetBrains.Rd.Impl.Serializers.WriteString.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbCsvRow) obj);
    }
    public bool Equals(ArbCsvRow other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Cells.SequenceEqual(other.Cells);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Cells.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbCsvRow (");
      using (printer.IndentCookie()) {
        printer.Print("cells = "); Cells.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:12</p>
  /// </summary>
  public sealed class ArbEntry : IPrintable, IEquatable<ArbEntry>
  {
    //fields
    //public fields
    [NotNull] public string Key {get; private set;}
    [NotNull] public string Value {get; private set;}
    
    //private fields
    //primary constructor
    public ArbEntry(
      [NotNull] string key,
      [NotNull] string value
    )
    {
      if (key == null) throw new ArgumentNullException("key");
      if (value == null) throw new ArgumentNullException("value");
      
      Key = key;
      Value = value;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string key, [NotNull] out string value)
    {
      key = Key;
      value = Value;
    }
    //statics
    
    public static CtxReadDelegate<ArbEntry> Read = (ctx, reader) => 
    {
      var key = reader.ReadString();
      var value = reader.ReadString();
      var _result = new ArbEntry(key, value);
      return _result;
    };
    
    public static CtxWriteDelegate<ArbEntry> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Key);
      writer.Write(value.Value);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbEntry) obj);
    }
    public bool Equals(ArbEntry other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Key == other.Key && Value == other.Value;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Key.GetHashCode();
        hash = hash * 31 + Value.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbEntry (");
      using (printer.IndentCookie()) {
        printer.Print("key = "); Key.PrintEx(printer); printer.Println();
        printer.Print("value = "); Value.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:28</p>
  /// </summary>
  public sealed class ArbEntryUpdate : IPrintable, IEquatable<ArbEntryUpdate>
  {
    //fields
    //public fields
    [NotNull] public string Directory {get; private set;}
    [NotNull] public string Locale {get; private set;}
    [NotNull] public string Key {get; private set;}
    [NotNull] public string Value {get; private set;}
    
    //private fields
    //primary constructor
    public ArbEntryUpdate(
      [NotNull] string directory,
      [NotNull] string locale,
      [NotNull] string key,
      [NotNull] string value
    )
    {
      if (directory == null) throw new ArgumentNullException("directory");
      if (locale == null) throw new ArgumentNullException("locale");
      if (key == null) throw new ArgumentNullException("key");
      if (value == null) throw new ArgumentNullException("value");
      
      Directory = directory;
      Locale = locale;
      Key = key;
      Value = value;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string directory, [NotNull] out string locale, [NotNull] out string key, [NotNull] out string value)
    {
      directory = Directory;
      locale = Locale;
      key = Key;
      value = Value;
    }
    //statics
    
    public static CtxReadDelegate<ArbEntryUpdate> Read = (ctx, reader) => 
    {
      var directory = reader.ReadString();
      var locale = reader.ReadString();
      var key = reader.ReadString();
      var value = reader.ReadString();
      var _result = new ArbEntryUpdate(directory, locale, key, value);
      return _result;
    };
    
    public static CtxWriteDelegate<ArbEntryUpdate> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Directory);
      writer.Write(value.Locale);
      writer.Write(value.Key);
      writer.Write(value.Value);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbEntryUpdate) obj);
    }
    public bool Equals(ArbEntryUpdate other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Directory == other.Directory && Locale == other.Locale && Key == other.Key && Value == other.Value;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Directory.GetHashCode();
        hash = hash * 31 + Locale.GetHashCode();
        hash = hash * 31 + Key.GetHashCode();
        hash = hash * 31 + Value.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbEntryUpdate (");
      using (printer.IndentCookie()) {
        printer.Print("directory = "); Directory.PrintEx(printer); printer.Println();
        printer.Print("locale = "); Locale.PrintEx(printer); printer.Println();
        printer.Print("key = "); Key.PrintEx(printer); printer.Println();
        printer.Print("value = "); Value.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:137</p>
  /// </summary>
  public sealed class ArbKeyInfo : IPrintable, IEquatable<ArbKeyInfo>
  {
    //fields
    //public fields
    [NotNull] public string Key {get; private set;}
    public bool IsParametric {get; private set;}
    [CanBeNull] public string Description {get; private set;}
    [CanBeNull] public string ArbFilePath {get; private set;}
    public int LineNumber {get; private set;}
    [CanBeNull] public string XmlDoc {get; private set;}
    
    //private fields
    //primary constructor
    public ArbKeyInfo(
      [NotNull] string key,
      bool isParametric,
      [CanBeNull] string description,
      [CanBeNull] string arbFilePath,
      int lineNumber,
      [CanBeNull] string xmlDoc
    )
    {
      if (key == null) throw new ArgumentNullException("key");
      
      Key = key;
      IsParametric = isParametric;
      Description = description;
      ArbFilePath = arbFilePath;
      LineNumber = lineNumber;
      XmlDoc = xmlDoc;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string key, out bool isParametric, [CanBeNull] out string description, [CanBeNull] out string arbFilePath, out int lineNumber, [CanBeNull] out string xmlDoc)
    {
      key = Key;
      isParametric = IsParametric;
      description = Description;
      arbFilePath = ArbFilePath;
      lineNumber = LineNumber;
      xmlDoc = XmlDoc;
    }
    //statics
    
    public static CtxReadDelegate<ArbKeyInfo> Read = (ctx, reader) => 
    {
      var key = reader.ReadString();
      var isParametric = reader.ReadBool();
      var description = ReadStringNullable(ctx, reader);
      var arbFilePath = ReadStringNullable(ctx, reader);
      var lineNumber = reader.ReadInt();
      var xmlDoc = ReadStringNullable(ctx, reader);
      var _result = new ArbKeyInfo(key, isParametric, description, arbFilePath, lineNumber, xmlDoc);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    
    public static CtxWriteDelegate<ArbKeyInfo> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Key);
      writer.Write(value.IsParametric);
      WriteStringNullable(ctx, writer, value.Description);
      WriteStringNullable(ctx, writer, value.ArbFilePath);
      writer.Write(value.LineNumber);
      WriteStringNullable(ctx, writer, value.XmlDoc);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbKeyInfo) obj);
    }
    public bool Equals(ArbKeyInfo other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Key == other.Key && IsParametric == other.IsParametric && Equals(Description, other.Description) && Equals(ArbFilePath, other.ArbFilePath) && LineNumber == other.LineNumber && Equals(XmlDoc, other.XmlDoc);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Key.GetHashCode();
        hash = hash * 31 + IsParametric.GetHashCode();
        hash = hash * 31 + (Description != null ? Description.GetHashCode() : 0);
        hash = hash * 31 + (ArbFilePath != null ? ArbFilePath.GetHashCode() : 0);
        hash = hash * 31 + LineNumber.GetHashCode();
        hash = hash * 31 + (XmlDoc != null ? XmlDoc.GetHashCode() : 0);
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbKeyInfo (");
      using (printer.IndentCookie()) {
        printer.Print("key = "); Key.PrintEx(printer); printer.Println();
        printer.Print("isParametric = "); IsParametric.PrintEx(printer); printer.Println();
        printer.Print("description = "); Description.PrintEx(printer); printer.Println();
        printer.Print("arbFilePath = "); ArbFilePath.PrintEx(printer); printer.Println();
        printer.Print("lineNumber = "); LineNumber.PrintEx(printer); printer.Println();
        printer.Print("xmlDoc = "); XmlDoc.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:36</p>
  /// </summary>
  public sealed class ArbKeyRename : IPrintable, IEquatable<ArbKeyRename>
  {
    //fields
    //public fields
    [NotNull] public string Directory {get; private set;}
    [NotNull] public string OldKey {get; private set;}
    [NotNull] public string NewKey {get; private set;}
    
    //private fields
    //primary constructor
    public ArbKeyRename(
      [NotNull] string directory,
      [NotNull] string oldKey,
      [NotNull] string newKey
    )
    {
      if (directory == null) throw new ArgumentNullException("directory");
      if (oldKey == null) throw new ArgumentNullException("oldKey");
      if (newKey == null) throw new ArgumentNullException("newKey");
      
      Directory = directory;
      OldKey = oldKey;
      NewKey = newKey;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string directory, [NotNull] out string oldKey, [NotNull] out string newKey)
    {
      directory = Directory;
      oldKey = OldKey;
      newKey = NewKey;
    }
    //statics
    
    public static CtxReadDelegate<ArbKeyRename> Read = (ctx, reader) => 
    {
      var directory = reader.ReadString();
      var oldKey = reader.ReadString();
      var newKey = reader.ReadString();
      var _result = new ArbKeyRename(directory, oldKey, newKey);
      return _result;
    };
    
    public static CtxWriteDelegate<ArbKeyRename> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Directory);
      writer.Write(value.OldKey);
      writer.Write(value.NewKey);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbKeyRename) obj);
    }
    public bool Equals(ArbKeyRename other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Directory == other.Directory && OldKey == other.OldKey && NewKey == other.NewKey;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Directory.GetHashCode();
        hash = hash * 31 + OldKey.GetHashCode();
        hash = hash * 31 + NewKey.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbKeyRename (");
      using (printer.IndentCookie()) {
        printer.Print("directory = "); Directory.PrintEx(printer); printer.Println();
        printer.Print("oldKey = "); OldKey.PrintEx(printer); printer.Println();
        printer.Print("newKey = "); NewKey.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:20</p>
  /// </summary>
  public sealed class ArbLocaleData : IPrintable, IEquatable<ArbLocaleData>
  {
    //fields
    //public fields
    [NotNull] public string Locale {get; private set;}
    [NotNull] public string Directory {get; private set;}
    [NotNull] public string FilePath {get; private set;}
    [NotNull] public List<ArbEntry> Entries {get; private set;}
    
    //private fields
    //primary constructor
    public ArbLocaleData(
      [NotNull] string locale,
      [NotNull] string directory,
      [NotNull] string filePath,
      [NotNull] List<ArbEntry> entries
    )
    {
      if (locale == null) throw new ArgumentNullException("locale");
      if (directory == null) throw new ArgumentNullException("directory");
      if (filePath == null) throw new ArgumentNullException("filePath");
      if (entries == null) throw new ArgumentNullException("entries");
      
      Locale = locale;
      Directory = directory;
      FilePath = filePath;
      Entries = entries;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string locale, [NotNull] out string directory, [NotNull] out string filePath, [NotNull] out List<ArbEntry> entries)
    {
      locale = Locale;
      directory = Directory;
      filePath = FilePath;
      entries = Entries;
    }
    //statics
    
    public static CtxReadDelegate<ArbLocaleData> Read = (ctx, reader) => 
    {
      var locale = reader.ReadString();
      var directory = reader.ReadString();
      var filePath = reader.ReadString();
      var entries = ReadArbEntryList(ctx, reader);
      var _result = new ArbLocaleData(locale, directory, filePath, entries);
      return _result;
    };
    public static CtxReadDelegate<List<ArbEntry>> ReadArbEntryList = ArbEntry.Read.List();
    
    public static CtxWriteDelegate<ArbLocaleData> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Locale);
      writer.Write(value.Directory);
      writer.Write(value.FilePath);
      WriteArbEntryList(ctx, writer, value.Entries);
    };
    public static  CtxWriteDelegate<List<ArbEntry>> WriteArbEntryList = ArbEntry.Write.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbLocaleData) obj);
    }
    public bool Equals(ArbLocaleData other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Locale == other.Locale && Directory == other.Directory && FilePath == other.FilePath && Entries.SequenceEqual(other.Entries);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Locale.GetHashCode();
        hash = hash * 31 + Directory.GetHashCode();
        hash = hash * 31 + FilePath.GetHashCode();
        hash = hash * 31 + Entries.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbLocaleData (");
      using (printer.IndentCookie()) {
        printer.Print("locale = "); Locale.PrintEx(printer); printer.Println();
        printer.Print("directory = "); Directory.PrintEx(printer); printer.Println();
        printer.Print("filePath = "); FilePath.PrintEx(printer); printer.Println();
        printer.Print("entries = "); Entries.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:43</p>
  /// </summary>
  public sealed class ArbNewKey : IPrintable, IEquatable<ArbNewKey>
  {
    //fields
    //public fields
    [NotNull] public string Directory {get; private set;}
    [NotNull] public string Key {get; private set;}
    
    //private fields
    //primary constructor
    public ArbNewKey(
      [NotNull] string directory,
      [NotNull] string key
    )
    {
      if (directory == null) throw new ArgumentNullException("directory");
      if (key == null) throw new ArgumentNullException("key");
      
      Directory = directory;
      Key = key;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string directory, [NotNull] out string key)
    {
      directory = Directory;
      key = Key;
    }
    //statics
    
    public static CtxReadDelegate<ArbNewKey> Read = (ctx, reader) => 
    {
      var directory = reader.ReadString();
      var key = reader.ReadString();
      var _result = new ArbNewKey(directory, key);
      return _result;
    };
    
    public static CtxWriteDelegate<ArbNewKey> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Directory);
      writer.Write(value.Key);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbNewKey) obj);
    }
    public bool Equals(ArbNewKey other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Directory == other.Directory && Key == other.Key;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Directory.GetHashCode();
        hash = hash * 31 + Key.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbNewKey (");
      using (printer.IndentCookie()) {
        printer.Print("directory = "); Directory.PrintEx(printer); printer.Println();
        printer.Print("key = "); Key.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:55</p>
  /// </summary>
  public sealed class ArbNewLocale : IPrintable, IEquatable<ArbNewLocale>
  {
    //fields
    //public fields
    [NotNull] public string Directory {get; private set;}
    [NotNull] public string Locale {get; private set;}
    
    //private fields
    //primary constructor
    public ArbNewLocale(
      [NotNull] string directory,
      [NotNull] string locale
    )
    {
      if (directory == null) throw new ArgumentNullException("directory");
      if (locale == null) throw new ArgumentNullException("locale");
      
      Directory = directory;
      Locale = locale;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string directory, [NotNull] out string locale)
    {
      directory = Directory;
      locale = Locale;
    }
    //statics
    
    public static CtxReadDelegate<ArbNewLocale> Read = (ctx, reader) => 
    {
      var directory = reader.ReadString();
      var locale = reader.ReadString();
      var _result = new ArbNewLocale(directory, locale);
      return _result;
    };
    
    public static CtxWriteDelegate<ArbNewLocale> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Directory);
      writer.Write(value.Locale);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbNewLocale) obj);
    }
    public bool Equals(ArbNewLocale other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Directory == other.Directory && Locale == other.Locale;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Directory.GetHashCode();
        hash = hash * 31 + Locale.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbNewLocale (");
      using (printer.IndentCookie()) {
        printer.Print("directory = "); Directory.PrintEx(printer); printer.Println();
        printer.Print("locale = "); Locale.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:147</p>
  /// </summary>
  public sealed class ArbOpenEditor : IPrintable, IEquatable<ArbOpenEditor>
  {
    //fields
    //public fields
    [NotNull] public string ArbDir {get; private set;}
    [NotNull] public string KeyFilter {get; private set;}
    
    //private fields
    //primary constructor
    public ArbOpenEditor(
      [NotNull] string arbDir,
      [NotNull] string keyFilter
    )
    {
      if (arbDir == null) throw new ArgumentNullException("arbDir");
      if (keyFilter == null) throw new ArgumentNullException("keyFilter");
      
      ArbDir = arbDir;
      KeyFilter = keyFilter;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string arbDir, [NotNull] out string keyFilter)
    {
      arbDir = ArbDir;
      keyFilter = KeyFilter;
    }
    //statics
    
    public static CtxReadDelegate<ArbOpenEditor> Read = (ctx, reader) => 
    {
      var arbDir = reader.ReadString();
      var keyFilter = reader.ReadString();
      var _result = new ArbOpenEditor(arbDir, keyFilter);
      return _result;
    };
    
    public static CtxWriteDelegate<ArbOpenEditor> Write = (ctx, writer, value) => 
    {
      writer.Write(value.ArbDir);
      writer.Write(value.KeyFilter);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbOpenEditor) obj);
    }
    public bool Equals(ArbOpenEditor other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ArbDir == other.ArbDir && KeyFilter == other.KeyFilter;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + ArbDir.GetHashCode();
        hash = hash * 31 + KeyFilter.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbOpenEditor (");
      using (printer.IndentCookie()) {
        printer.Print("arbDir = "); ArbDir.PrintEx(printer); printer.Println();
        printer.Print("keyFilter = "); KeyFilter.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:49</p>
  /// </summary>
  public sealed class ArbRemoveKey : IPrintable, IEquatable<ArbRemoveKey>
  {
    //fields
    //public fields
    [NotNull] public string Directory {get; private set;}
    [NotNull] public string Key {get; private set;}
    
    //private fields
    //primary constructor
    public ArbRemoveKey(
      [NotNull] string directory,
      [NotNull] string key
    )
    {
      if (directory == null) throw new ArgumentNullException("directory");
      if (key == null) throw new ArgumentNullException("key");
      
      Directory = directory;
      Key = key;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string directory, [NotNull] out string key)
    {
      directory = Directory;
      key = Key;
    }
    //statics
    
    public static CtxReadDelegate<ArbRemoveKey> Read = (ctx, reader) => 
    {
      var directory = reader.ReadString();
      var key = reader.ReadString();
      var _result = new ArbRemoveKey(directory, key);
      return _result;
    };
    
    public static CtxWriteDelegate<ArbRemoveKey> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Directory);
      writer.Write(value.Key);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbRemoveKey) obj);
    }
    public bool Equals(ArbRemoveKey other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Directory == other.Directory && Key == other.Key;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Directory.GetHashCode();
        hash = hash * 31 + Key.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbRemoveKey (");
      using (printer.IndentCookie()) {
        printer.Print("directory = "); Directory.PrintEx(printer); printer.Println();
        printer.Print("key = "); Key.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:74</p>
  /// </summary>
  public sealed class ArbTranslateRequest : IPrintable, IEquatable<ArbTranslateRequest>
  {
    //fields
    //public fields
    [NotNull] public string Directory {get; private set;}
    [NotNull] public AzureTranslationSettings Settings {get; private set;}
    [NotNull] public string SourceLocale {get; private set;}
    [NotNull] public string TargetLocale {get; private set;}
    [NotNull] public List<ArbTranslationItem> Items {get; private set;}
    [NotNull] public string Provider {get; private set;}
    
    //private fields
    //primary constructor
    public ArbTranslateRequest(
      [NotNull] string directory,
      [NotNull] AzureTranslationSettings settings,
      [NotNull] string sourceLocale,
      [NotNull] string targetLocale,
      [NotNull] List<ArbTranslationItem> items,
      [NotNull] string provider
    )
    {
      if (directory == null) throw new ArgumentNullException("directory");
      if (settings == null) throw new ArgumentNullException("settings");
      if (sourceLocale == null) throw new ArgumentNullException("sourceLocale");
      if (targetLocale == null) throw new ArgumentNullException("targetLocale");
      if (items == null) throw new ArgumentNullException("items");
      if (provider == null) throw new ArgumentNullException("provider");
      
      Directory = directory;
      Settings = settings;
      SourceLocale = sourceLocale;
      TargetLocale = targetLocale;
      Items = items;
      Provider = provider;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string directory, [NotNull] out AzureTranslationSettings settings, [NotNull] out string sourceLocale, [NotNull] out string targetLocale, [NotNull] out List<ArbTranslationItem> items, [NotNull] out string provider)
    {
      directory = Directory;
      settings = Settings;
      sourceLocale = SourceLocale;
      targetLocale = TargetLocale;
      items = Items;
      provider = Provider;
    }
    //statics
    
    public static CtxReadDelegate<ArbTranslateRequest> Read = (ctx, reader) => 
    {
      var directory = reader.ReadString();
      var settings = AzureTranslationSettings.Read(ctx, reader);
      var sourceLocale = reader.ReadString();
      var targetLocale = reader.ReadString();
      var items = ReadArbTranslationItemList(ctx, reader);
      var provider = reader.ReadString();
      var _result = new ArbTranslateRequest(directory, settings, sourceLocale, targetLocale, items, provider);
      return _result;
    };
    public static CtxReadDelegate<List<ArbTranslationItem>> ReadArbTranslationItemList = ArbTranslationItem.Read.List();
    
    public static CtxWriteDelegate<ArbTranslateRequest> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Directory);
      AzureTranslationSettings.Write(ctx, writer, value.Settings);
      writer.Write(value.SourceLocale);
      writer.Write(value.TargetLocale);
      WriteArbTranslationItemList(ctx, writer, value.Items);
      writer.Write(value.Provider);
    };
    public static  CtxWriteDelegate<List<ArbTranslationItem>> WriteArbTranslationItemList = ArbTranslationItem.Write.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbTranslateRequest) obj);
    }
    public bool Equals(ArbTranslateRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Directory == other.Directory && Equals(Settings, other.Settings) && SourceLocale == other.SourceLocale && TargetLocale == other.TargetLocale && Items.SequenceEqual(other.Items) && Provider == other.Provider;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Directory.GetHashCode();
        hash = hash * 31 + Settings.GetHashCode();
        hash = hash * 31 + SourceLocale.GetHashCode();
        hash = hash * 31 + TargetLocale.GetHashCode();
        hash = hash * 31 + Items.ContentHashCode();
        hash = hash * 31 + Provider.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbTranslateRequest (");
      using (printer.IndentCookie()) {
        printer.Print("directory = "); Directory.PrintEx(printer); printer.Println();
        printer.Print("settings = "); Settings.PrintEx(printer); printer.Println();
        printer.Print("sourceLocale = "); SourceLocale.PrintEx(printer); printer.Println();
        printer.Print("targetLocale = "); TargetLocale.PrintEx(printer); printer.Println();
        printer.Print("items = "); Items.PrintEx(printer); printer.Println();
        printer.Print("provider = "); Provider.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:88</p>
  /// </summary>
  public sealed class ArbTranslateResponse : IPrintable, IEquatable<ArbTranslateResponse>
  {
    //fields
    //public fields
    public bool Success {get; private set;}
    [CanBeNull] public string ErrorMessage {get; private set;}
    [NotNull] public List<ArbTranslatedItem> Items {get; private set;}
    
    //private fields
    //primary constructor
    public ArbTranslateResponse(
      bool success,
      [CanBeNull] string errorMessage,
      [NotNull] List<ArbTranslatedItem> items
    )
    {
      if (items == null) throw new ArgumentNullException("items");
      
      Success = success;
      ErrorMessage = errorMessage;
      Items = items;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out bool success, [CanBeNull] out string errorMessage, [NotNull] out List<ArbTranslatedItem> items)
    {
      success = Success;
      errorMessage = ErrorMessage;
      items = Items;
    }
    //statics
    
    public static CtxReadDelegate<ArbTranslateResponse> Read = (ctx, reader) => 
    {
      var success = reader.ReadBool();
      var errorMessage = ReadStringNullable(ctx, reader);
      var items = ReadArbTranslatedItemList(ctx, reader);
      var _result = new ArbTranslateResponse(success, errorMessage, items);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    public static CtxReadDelegate<List<ArbTranslatedItem>> ReadArbTranslatedItemList = ArbTranslatedItem.Read.List();
    
    public static CtxWriteDelegate<ArbTranslateResponse> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Success);
      WriteStringNullable(ctx, writer, value.ErrorMessage);
      WriteArbTranslatedItemList(ctx, writer, value.Items);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    public static  CtxWriteDelegate<List<ArbTranslatedItem>> WriteArbTranslatedItemList = ArbTranslatedItem.Write.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbTranslateResponse) obj);
    }
    public bool Equals(ArbTranslateResponse other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Success == other.Success && Equals(ErrorMessage, other.ErrorMessage) && Items.SequenceEqual(other.Items);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Success.GetHashCode();
        hash = hash * 31 + (ErrorMessage != null ? ErrorMessage.GetHashCode() : 0);
        hash = hash * 31 + Items.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbTranslateResponse (");
      using (printer.IndentCookie()) {
        printer.Print("success = "); Success.PrintEx(printer); printer.Println();
        printer.Print("errorMessage = "); ErrorMessage.PrintEx(printer); printer.Println();
        printer.Print("items = "); Items.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:83</p>
  /// </summary>
  public sealed class ArbTranslatedItem : IPrintable, IEquatable<ArbTranslatedItem>
  {
    //fields
    //public fields
    [NotNull] public string Key {get; private set;}
    [NotNull] public string TranslatedText {get; private set;}
    
    //private fields
    //primary constructor
    public ArbTranslatedItem(
      [NotNull] string key,
      [NotNull] string translatedText
    )
    {
      if (key == null) throw new ArgumentNullException("key");
      if (translatedText == null) throw new ArgumentNullException("translatedText");
      
      Key = key;
      TranslatedText = translatedText;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string key, [NotNull] out string translatedText)
    {
      key = Key;
      translatedText = TranslatedText;
    }
    //statics
    
    public static CtxReadDelegate<ArbTranslatedItem> Read = (ctx, reader) => 
    {
      var key = reader.ReadString();
      var translatedText = reader.ReadString();
      var _result = new ArbTranslatedItem(key, translatedText);
      return _result;
    };
    
    public static CtxWriteDelegate<ArbTranslatedItem> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Key);
      writer.Write(value.TranslatedText);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbTranslatedItem) obj);
    }
    public bool Equals(ArbTranslatedItem other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Key == other.Key && TranslatedText == other.TranslatedText;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Key.GetHashCode();
        hash = hash * 31 + TranslatedText.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbTranslatedItem (");
      using (printer.IndentCookie()) {
        printer.Print("key = "); Key.PrintEx(printer); printer.Println();
        printer.Print("translatedText = "); TranslatedText.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:68</p>
  /// </summary>
  public sealed class ArbTranslationItem : IPrintable, IEquatable<ArbTranslationItem>
  {
    //fields
    //public fields
    [NotNull] public string Key {get; private set;}
    [NotNull] public string SourceText {get; private set;}
    [CanBeNull] public string Description {get; private set;}
    
    //private fields
    //primary constructor
    public ArbTranslationItem(
      [NotNull] string key,
      [NotNull] string sourceText,
      [CanBeNull] string description
    )
    {
      if (key == null) throw new ArgumentNullException("key");
      if (sourceText == null) throw new ArgumentNullException("sourceText");
      
      Key = key;
      SourceText = sourceText;
      Description = description;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string key, [NotNull] out string sourceText, [CanBeNull] out string description)
    {
      key = Key;
      sourceText = SourceText;
      description = Description;
    }
    //statics
    
    public static CtxReadDelegate<ArbTranslationItem> Read = (ctx, reader) => 
    {
      var key = reader.ReadString();
      var sourceText = reader.ReadString();
      var description = ReadStringNullable(ctx, reader);
      var _result = new ArbTranslationItem(key, sourceText, description);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    
    public static CtxWriteDelegate<ArbTranslationItem> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Key);
      writer.Write(value.SourceText);
      WriteStringNullable(ctx, writer, value.Description);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbTranslationItem) obj);
    }
    public bool Equals(ArbTranslationItem other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Key == other.Key && SourceText == other.SourceText && Equals(Description, other.Description);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Key.GetHashCode();
        hash = hash * 31 + SourceText.GetHashCode();
        hash = hash * 31 + (Description != null ? Description.GetHashCode() : 0);
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbTranslationItem (");
      using (printer.IndentCookie()) {
        printer.Print("key = "); Key.PrintEx(printer); printer.Println();
        printer.Print("sourceText = "); SourceText.PrintEx(printer); printer.Println();
        printer.Print("description = "); Description.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:60</p>
  /// </summary>
  public sealed class AzureTranslationSettings : IPrintable, IEquatable<AzureTranslationSettings>
  {
    //fields
    //public fields
    [NotNull] public string Endpoint {get; private set;}
    [NotNull] public string DeploymentName {get; private set;}
    [NotNull] public string ApiKey {get; private set;}
    [NotNull] public string CustomPrompt {get; private set;}
    public float Temperature {get; private set;}
    
    //private fields
    //primary constructor
    public AzureTranslationSettings(
      [NotNull] string endpoint,
      [NotNull] string deploymentName,
      [NotNull] string apiKey,
      [NotNull] string customPrompt,
      float temperature
    )
    {
      if (endpoint == null) throw new ArgumentNullException("endpoint");
      if (deploymentName == null) throw new ArgumentNullException("deploymentName");
      if (apiKey == null) throw new ArgumentNullException("apiKey");
      if (customPrompt == null) throw new ArgumentNullException("customPrompt");
      
      Endpoint = endpoint;
      DeploymentName = deploymentName;
      ApiKey = apiKey;
      CustomPrompt = customPrompt;
      Temperature = temperature;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string endpoint, [NotNull] out string deploymentName, [NotNull] out string apiKey, [NotNull] out string customPrompt, out float temperature)
    {
      endpoint = Endpoint;
      deploymentName = DeploymentName;
      apiKey = ApiKey;
      customPrompt = CustomPrompt;
      temperature = Temperature;
    }
    //statics
    
    public static CtxReadDelegate<AzureTranslationSettings> Read = (ctx, reader) => 
    {
      var endpoint = reader.ReadString();
      var deploymentName = reader.ReadString();
      var apiKey = reader.ReadString();
      var customPrompt = reader.ReadString();
      var temperature = reader.ReadFloat();
      var _result = new AzureTranslationSettings(endpoint, deploymentName, apiKey, customPrompt, temperature);
      return _result;
    };
    
    public static CtxWriteDelegate<AzureTranslationSettings> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Endpoint);
      writer.Write(value.DeploymentName);
      writer.Write(value.ApiKey);
      writer.Write(value.CustomPrompt);
      writer.Write(value.Temperature);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((AzureTranslationSettings) obj);
    }
    public bool Equals(AzureTranslationSettings other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Endpoint == other.Endpoint && DeploymentName == other.DeploymentName && ApiKey == other.ApiKey && CustomPrompt == other.CustomPrompt && Temperature == other.Temperature;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Endpoint.GetHashCode();
        hash = hash * 31 + DeploymentName.GetHashCode();
        hash = hash * 31 + ApiKey.GetHashCode();
        hash = hash * 31 + CustomPrompt.GetHashCode();
        hash = hash * 31 + Temperature.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("AzureTranslationSettings (");
      using (printer.IndentCookie()) {
        printer.Print("endpoint = "); Endpoint.PrintEx(printer); printer.Println();
        printer.Print("deploymentName = "); DeploymentName.PrintEx(printer); printer.Println();
        printer.Print("apiKey = "); ApiKey.PrintEx(printer); printer.Println();
        printer.Print("customPrompt = "); CustomPrompt.PrintEx(printer); printer.Println();
        printer.Print("temperature = "); Temperature.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
