//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:9</p>
  /// </summary>
  public class ArbModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<Unit, List<ArbLocaleData>> GetArbData => _GetArbData;
    
    //private fields
    [NotNull] private readonly RdCall<Unit, List<ArbLocaleData>> _GetArbData;
    
    //primary constructor
    private ArbModel(
      [NotNull] RdCall<Unit, List<ArbLocaleData>> getArbData
    )
    {
      if (getArbData == null) throw new ArgumentNullException("getArbData");
      
      _GetArbData = getArbData;
      BindableChildren.Add(new KeyValuePair<string, object>("getArbData", _GetArbData));
    }
    //secondary constructor
    internal ArbModel (
    ) : this (
      new RdCall<Unit, List<ArbLocaleData>>(JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid, ReadArbLocaleDataList, WriteArbLocaleDataList)
    ) {}
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<List<ArbLocaleData>> ReadArbLocaleDataList = ArbLocaleData.Read.List();
    
    public static  CtxWriteDelegate<List<ArbLocaleData>> WriteArbLocaleDataList = ArbLocaleData.Write.List();
    
    protected override long SerializationHash => -1039800800516086927L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("ArbModel (");
      using (printer.IndentCookie()) {
        printer.Print("getArbData = "); _GetArbData.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionArbModelEx
   {
    public static ArbModel GetArbModel(this Solution solution)
    {
      return solution.GetOrCreateExtension("arbModel", () => new ArbModel());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:12</p>
  /// </summary>
  public sealed class ArbEntry : IPrintable, IEquatable<ArbEntry>
  {
    //fields
    //public fields
    [NotNull] public string Key {get; private set;}
    [NotNull] public string Value {get; private set;}
    
    //private fields
    //primary constructor
    public ArbEntry(
      [NotNull] string key,
      [NotNull] string value
    )
    {
      if (key == null) throw new ArgumentNullException("key");
      if (value == null) throw new ArgumentNullException("value");
      
      Key = key;
      Value = value;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string key, [NotNull] out string value)
    {
      key = Key;
      value = Value;
    }
    //statics
    
    public static CtxReadDelegate<ArbEntry> Read = (ctx, reader) => 
    {
      var key = reader.ReadString();
      var value = reader.ReadString();
      var _result = new ArbEntry(key, value);
      return _result;
    };
    
    public static CtxWriteDelegate<ArbEntry> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Key);
      writer.Write(value.Value);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbEntry) obj);
    }
    public bool Equals(ArbEntry other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Key == other.Key && Value == other.Value;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Key.GetHashCode();
        hash = hash * 31 + Value.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbEntry (");
      using (printer.IndentCookie()) {
        printer.Print("key = "); Key.PrintEx(printer); printer.Println();
        printer.Print("value = "); Value.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: ArbModel.kt:18</p>
  /// </summary>
  public sealed class ArbLocaleData : IPrintable, IEquatable<ArbLocaleData>
  {
    //fields
    //public fields
    [NotNull] public string Locale {get; private set;}
    [NotNull] public List<ArbEntry> Entries {get; private set;}
    
    //private fields
    //primary constructor
    public ArbLocaleData(
      [NotNull] string locale,
      [NotNull] List<ArbEntry> entries
    )
    {
      if (locale == null) throw new ArgumentNullException("locale");
      if (entries == null) throw new ArgumentNullException("entries");
      
      Locale = locale;
      Entries = entries;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string locale, [NotNull] out List<ArbEntry> entries)
    {
      locale = Locale;
      entries = Entries;
    }
    //statics
    
    public static CtxReadDelegate<ArbLocaleData> Read = (ctx, reader) => 
    {
      var locale = reader.ReadString();
      var entries = ReadArbEntryList(ctx, reader);
      var _result = new ArbLocaleData(locale, entries);
      return _result;
    };
    public static CtxReadDelegate<List<ArbEntry>> ReadArbEntryList = ArbEntry.Read.List();
    
    public static CtxWriteDelegate<ArbLocaleData> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Locale);
      WriteArbEntryList(ctx, writer, value.Entries);
    };
    public static  CtxWriteDelegate<List<ArbEntry>> WriteArbEntryList = ArbEntry.Write.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ArbLocaleData) obj);
    }
    public bool Equals(ArbLocaleData other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Locale == other.Locale && Entries.SequenceEqual(other.Entries);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Locale.GetHashCode();
        hash = hash * 31 + Entries.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ArbLocaleData (");
      using (printer.IndentCookie()) {
        printer.Print("locale = "); Locale.PrintEx(printer); printer.Println();
        printer.Print("entries = "); Entries.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
