// <auto-generated/>
// Available locales: en
#nullable enable

namespace ExampleThree.Localizations;

public partial class AppLocale : global::Arb.NET.IArbLocale {
    private readonly System.Globalization.CultureInfo _culture;

    public AppLocale(System.Globalization.CultureInfo culture) {
        _culture = culture;
    }

    private static string ResolveLocale(System.Globalization.CultureInfo culture) {
        var name = culture.Name.Replace("-", "_");
        return name switch {
            "en" => "en",
            _ => TryParent(culture)
        };
    }

    private static string TryParent(System.Globalization.CultureInfo culture) {
        if (!culture.IsNeutralCulture) {
            var parent = culture.Parent;
            if (!string.IsNullOrEmpty(parent.Name))
                return ResolveLocale(parent);
        }
        throw new System.NotSupportedException(
            $"No localization found for '{culture.Name}'. Available: en");
    }

    /// <summary>
    /// <list type="table">
    /// <listheader><term>Locale</term><description>Value</description></listheader>
    /// <item><term>en</term><description>Arb.NET Example Three</description></item>
    /// </list>
    /// </summary>
    public string AppTitle => ResolveLocale(_culture) switch {
        "en" => AppLocale_en.AppTitle,
        _ => throw new System.NotSupportedException(
            $"No localization found for '{_culture.Name}'. Available: en")
    };

    /// <summary>
    /// <list type="table">
    /// <listheader><term>Locale</term><description>Value</description></listheader>
    /// <item><term>en</term><description>Another string</description></item>
    /// </list>
    /// </summary>
    public string AnotherString => ResolveLocale(_culture) switch {
        "en" => AppLocale_en.AnotherString,
        _ => throw new System.NotSupportedException(
            $"No localization found for '{_culture.Name}'. Available: en")
    };

    /// <summary>Returns the localized string for the given raw ARB key, or null if not found.</summary>
    public string? this[string? key] => key switch {
        "appTitle" => AppTitle,
        "AppTitle" => AppTitle,
        "anotherString" => AnotherString,
        "AnotherString" => AnotherString,
        _ => null
    };
}
