// <auto-generated/>
// Locale: en

namespace ExampleThree.Localizations;

public static class AppLocale_en {

    /// <returns>Arb.NET Example Three</returns>
    public static string AppTitle
        => "Arb.NET Example Three";

    /// <returns>Another string</returns>
    public static string AnotherString
        => "Another string";
}
