// <auto-generated/>
// Available locales: cs, en, pl
#nullable enable

namespace ExampleFive;

public partial class AppLocale : global::Arb.NET.IArbLocale {
    private readonly System.Globalization.CultureInfo _culture;

    public AppLocale(System.Globalization.CultureInfo culture) {
        _culture = culture;
    }

    private static string ResolveLocale(System.Globalization.CultureInfo culture) {
        var name = culture.Name.Replace("-", "_");
        return name switch {
            "cs" => "cs",
            "en" => "en",
            "pl" => "pl",
            _ => TryParent(culture)
        };
    }

    private static string TryParent(System.Globalization.CultureInfo culture) {
        if (!culture.IsNeutralCulture) {
            var parent = culture.Parent;
            if (!string.IsNullOrEmpty(parent.Name))
                return ResolveLocale(parent);
        }
        throw new System.NotSupportedException(
            $"No localization found for '{culture.Name}'. Available: cs, en, pl");
    }

    /// <summary>
    /// <list type="table">
    /// <listheader><term>Locale</term><description>Value</description></listheader>
    /// <item><term>cs</term><description>Arb.NET Příklad 5 Přeloženo!</description></item>
    /// <item><term>en</term><description>Arb.NET Example Five Localized</description></item>
    /// <item><term>pl</term><description></description></item>
    /// </list>
    /// </summary>
    public string AppTitle => ResolveLocale(_culture) switch {
        "cs" => AppLocale_cs.AppTitle,
        "en" => AppLocale_en.AppTitle,
        "pl" => AppLocale_pl.AppTitle,
        _ => throw new System.NotSupportedException(
            $"No localization found for '{_culture.Name}'. Available: cs, en, pl")
    };

    /// <summary>
    /// <list type="table">
    /// <listheader><term>Locale</term><description>Value</description></listheader>
    /// <item><term>cs</term><description>Ahoj, {name}!</description></item>
    /// <item><term>en</term><description>Hello, {name}!</description></item>
    /// <item><term>pl</term><description></description></item>
    /// </list>
    /// </summary>
    public string Greeting(object name) {
        return ResolveLocale(_culture) switch {
            "cs" => AppLocale_cs.Greeting(name),
            "en" => AppLocale_en.Greeting(name),
            "pl" => AppLocale_pl.Greeting(name),
            _ => throw new System.NotSupportedException(
                $"No localization found for '{_culture.Name}'. Available: cs, en, pl")
        };
    }

    /// <summary>
    /// <list type="table">
    /// <listheader><term>Locale</term><description>Value</description></listheader>
    /// <item><term>cs</term><description>This translates to nothing.</description></item>
    /// <item><term>en</term><description></description></item>
    /// <item><term>pl</term><description></description></item>
    /// </list>
    /// </summary>
    public string Nonprimary => ResolveLocale(_culture) switch {
        "cs" => AppLocale_cs.Nonprimary,
        "en" => AppLocale_en.Nonprimary,
        "pl" => AppLocale_pl.Nonprimary,
        _ => throw new System.NotSupportedException(
            $"No localization found for '{_culture.Name}'. Available: cs, en, pl")
    };


#warning Key 'pluralpls': Value looks like a plural for 'count' but the syntax is invalid. Ensure forms are separated by spaces (not commas) and use '=N{{...}}' syntax (not 'N={{...}}').
    public string Pluralpls() {
        throw new System.NotSupportedException("Key 'pluralpls': Value looks like a plural for 'count' but the syntax is invalid. Ensure forms are separated by spaces (not commas) and use '=N{{...}}' syntax (not 'N={{...}}').");
    }

    /// <summary>
    /// <list type="table">
    /// <listheader><term>Locale</term><description>Value</description></listheader>
    /// <item><term>cs</term><description>value not present</description></item>
    /// <item><term>en</term><description>calue {value}</description></item>
    /// <item><term>pl</term><description>-</description></item>
    /// </list>
    /// </summary>
    public string Temp(object value) {
        return ResolveLocale(_culture) switch {
            "cs" => AppLocale_cs.Temp(value),
            "en" => AppLocale_en.Temp(value),
            "pl" => AppLocale_pl.Temp(value),
            _ => throw new System.NotSupportedException(
                $"No localization found for '{_culture.Name}'. Available: cs, en, pl")
        };
    }

    /// <summary>Returns the localized string for the given raw ARB key, or null if not found.</summary>
    public string? this[string? key] => key switch {
        "appTitle" => AppTitle,
        "AppTitle" => AppTitle,
        "nonprimary" => Nonprimary,
        "Nonprimary" => Nonprimary,
        _ => null
    };
}
