// <auto-generated/>
// Locale: cs

namespace ExampleFive;

public static class AppLocale_cs {

    /// <returns>Arb.NET Příklad 5 Přeloženo!</returns>
    public static string AppTitle
        => "Arb.NET Příklad 5 Přeloženo!";

    /// <returns>Ahoj, {name}!</returns>
    public static string Greeting(object name) {
        return $"Ahoj, " + name?.ToString() + "!";
    }

    /// <returns>This translates to nothing.</returns>
    public static string Nonprimary
        => "This translates to nothing.";

    /// <returns></returns>
    public static string Pluralpls
        => "";

    /// <returns>value not present</returns>
    public static string Temp(object value) {
        return "value not present";
    }
}
