// <auto-generated/>
// Locale: en

namespace ExampleFive;

public static class AppLocale_en {

    /// <returns>Arb.NET Example Five Localized</returns>
    public static string AppTitle
        => "Arb.NET Example Five Localized";

    /// <returns>Hello, {name}!</returns>
    public static string Greeting(object name) {
        return $"Hello, " + name?.ToString() + "!";
    }
}
