// <auto-generated/>
// Locale: pl

namespace ExampleFive;

public static class AppLocale_pl {

    /// <returns></returns>
    public static string AppTitle
        => "";

    /// <returns></returns>
    public static string Greeting(object name) {
        return "";
    }

    /// <returns></returns>
    public static string Nonprimary
        => "";

    /// <returns></returns>
    public static string Pluralpls
        => "";

    /// <returns>-</returns>
    public static string Temp(object value) {
        return "-";
    }
}
