#if !ARB_GENERATOR
using System.IO;
#endif
using System.Text;

namespace Arb.NET;

/// <summary>
/// Generates C# code from parsed .arb documents
/// </summary>
public class ArbCodeGenerator {
    /// <summary>
    /// Generates a C# class from an ARB document
    /// </summary>
    public string GenerateClass(ArbDocument document, string className, string namespaceName) {
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Locale: {document.Locale}");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"public static class {className} {{");

        foreach (ArbEntry entry in document.Entries.Values) {
            GenerateEntry(sb, entry);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

#if !ARB_GENERATOR
    /// <summary>
    /// Parses an .arb file and writes a generated C# file to <paramref name="outputPath"/>
    /// </summary>
    public void GenerateClassFile(string arbFilePath, string outputPath, string className, string namespaceName) {
        ArbParseResult result = new ArbParser().Parse(arbFilePath);
        if (!result.ValidationResults.IsValid) {
            // TODO(handle)
            return;
        }
        string source = GenerateClass(result.Document!, className, namespaceName);
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? ".");
        File.WriteAllText(outputPath, source);
    }
#endif

    private static void GenerateEntry(StringBuilder sb, ArbEntry entry) {
        if (entry.IsParametric(out List<ArbParameterDefinition> defs)) {
            string paramList = BuildParamList(defs);

            sb.AppendLine();
            BuildSummaryTag(sb, entry);
            sb.AppendLine($"    public static string {StringHelper.ToPascalCase(entry.Key)}({paramList}) {{");
            BuildPluralizationDefs(sb, defs);
            sb.AppendLine($"        return {BuildFormattedString(entry, defs)};");
            sb.AppendLine($"    }}");
        }
        else {
            sb.AppendLine();
            BuildSummaryTag(sb, entry);
            sb.AppendLine($"    public static string {StringHelper.ToPascalCase(entry.Key)}\n" +
                          $"        => \"{StringHelper.JsonString(entry.Value)}\";");
        }
    }

    private static string BuildParamList(List<ArbParameterDefinition> names) {
        return string.Join(", ", names.Select(s => {
            if (s is not ArbPluralizationParameterDefinition) {
                return "object " + s.Name;
            }
            else {
                return "int " + s.Name;
            }
        }));
    }

    private static string BuildFormattedString(ArbEntry entry, List<ArbParameterDefinition> defs) {
        StringBuilder sb = new();
        int index = 0;

        sb.Append('$');
        sb.Append('"');

        while (index < entry.Value.Length) {
            char current = entry.Value[index];

            if (current == '\\') {
                // Handle escaped characters
                if (index + 1 < entry.Value.Length) {
                    if (entry.Value[index + 1] == '\\') {
                        // Append the escape char itself
                        sb.Append(current);
                    }
                    sb.Append(entry.Value[index + 1]);
                    index += 2;
                    continue;
                }
            }

            if (defs.Find(f => f.StartIndex == index) is { } def) {
                if (def is not ArbPluralizationParameterDefinition) {
                    sb.Append("\"");
                    sb.Append(" + ");
                    sb.Append(def.Name);
                    sb.Append("?.ToString()");
                    sb.Append(" + ");
                    sb.Append("\"");
                    index = def.EndIndex;
                    continue;
                }
                else {
                    sb.Append("\"");
                    sb.Append(" + ");
                    sb.Append($"@selectedContent_{def.Name}");
                    sb.Append(" + ");
                    sb.Append("\"");
                    index = def.EndIndex;
                    continue;
                }
            }

            sb.Append(current);

            index++;
        }

        sb.Append('"');
        return sb.ToString();
    }

    private static void BuildPluralizationDefs(StringBuilder sb, List<ArbParameterDefinition> defs) {
        foreach (ArbParameterDefinition? def in defs) {
            if (def is not ArbPluralizationParameterDefinition pluralDef) continue;

            sb.AppendLine($"        var @selectedContent_{pluralDef.Name} = ({pluralDef.Name}) switch {{");
            foreach (KeyValuePair<int, string> form in pluralDef.CountableParameters) {
                string escapeString = StringHelper.JsonString(form.Value);
                escapeString = escapeString.Replace($"{{{def.Name}}}", $"\" + {def.Name}.ToString() + \"");
                sb.AppendLine($"            {form.Key} => \"{escapeString}\",");
            }
            string escapeOtherString = StringHelper.JsonString(pluralDef.OtherParameter);
            escapeOtherString = escapeOtherString.Replace($"{{{def.Name}}}", $"\" + {def.Name}.ToString() + \"");
            sb.AppendLine($"            _ => \"{escapeOtherString}\"");
            sb.AppendLine("        };");
        }
    }

    private static void BuildSummaryTag(StringBuilder sb, ArbEntry entry) {
        string? description = entry.Metadata?.Description;
        string renderedValue = StringHelper.XmlEscape(RenderEntryValueForDoc(entry));

        if (!string.IsNullOrWhiteSpace(description)) {
            sb.AppendLine($"    /// <summary>{description}</summary>");
        }
        sb.AppendLine($"    /// <returns>{renderedValue}</returns>");
    }

    /// <summary>
    /// Generates a dispatcher class that routes localization calls to the correct
    /// locale-specific static class based on a <see cref="System.Globalization.CultureInfo"/>.
    /// The <paramref name="defaultLocale"/> document is authoritative for entry signatures.
    /// When <paramref name="enumLocalizations"/> is provided, a <c>Localize(EnumType)</c>
    /// overload is emitted for each enum so callers can write <c>l.Localize(myEnumValue)</c>.
    /// </summary>
    internal string GenerateDispatcherClass(
        IReadOnlyList<(ArbDocument Document, string ClassName)> locales,
        ArbDocument defaultLocale,
        string baseClassName,
        string namespaceName,
        IReadOnlyList<EnumLocalizationInfo>? enumLocalizations = null
    ) {
        StringBuilder sb = new();
        string availableLocales = string.Join(", ", locales.Select(l => l.Document.Locale));

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Available locales: {availableLocales}");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"public class {baseClassName} {{");
        sb.AppendLine($"    private readonly System.Globalization.CultureInfo _culture;");
        sb.AppendLine();
        sb.AppendLine($"    public {baseClassName}(System.Globalization.CultureInfo culture) {{");
        sb.AppendLine($"        _culture = culture;");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // ResolveLocale — maps a CultureInfo to a normalized locale key
        sb.AppendLine($"    private static string ResolveLocale(System.Globalization.CultureInfo culture) {{");
        sb.AppendLine($"        var name = culture.Name.Replace(\"-\", \"_\");");
        sb.AppendLine($"        return name switch {{");
        foreach ((ArbDocument doc, string _) in locales) {
            string normalized = StringHelper.JsonString(StringHelper.NormalizeLocale(doc.Locale));
            sb.AppendLine($"            \"{normalized}\" => \"{normalized}\",");
        }
        sb.AppendLine($"            _ => TryParent(culture)");
        sb.AppendLine($"        }};");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // TryParent — walks up to neutral culture, then throws
        sb.AppendLine($"    private static string TryParent(System.Globalization.CultureInfo culture) {{");
        sb.AppendLine($"        if (!culture.IsNeutralCulture) {{");
        sb.AppendLine($"            var parent = culture.Parent;");
        sb.AppendLine($"            if (!string.IsNullOrEmpty(parent.Name))");
        sb.AppendLine($"                return ResolveLocale(parent);");
        sb.AppendLine($"        }}");
        sb.AppendLine($"        throw new System.NotSupportedException(");
        sb.AppendLine($"            $\"No localization found for '{{culture.Name}}'. Available: {availableLocales}\");");
        sb.AppendLine($"    }}");

        // Build a lookup: locale key → class name, for use in switch arms
        Dictionary<string, string> localeToClass = locales.ToDictionary(
            l => StringHelper.NormalizeLocale(l.Document.Locale),
            l => l.ClassName);

        // Emit one member per entry in the default-locale document
        foreach (ArbEntry? entry in defaultLocale.Entries.Values) {
            sb.AppendLine();
            GenerateDispatcherEntry(sb, entry, locales, localeToClass, availableLocales);
        }

        // Emit Localize(EnumType) overloads for each [ArbLocalize] enum
        if (enumLocalizations != null) {
            foreach (EnumLocalizationInfo info in enumLocalizations) {
                AppendEnumLocalizeMethod(sb, info.FullName, info.SimpleName, info.Members);
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateDispatcherEntry(
        StringBuilder sb,
        ArbEntry defaultEntry,
        IReadOnlyList<(ArbDocument Document, string ClassName)> locales,
        Dictionary<string, string> localeToClass,
        string availableLocales
    ) {

        bool isParametric = defaultEntry.IsParametric(out List<ArbParameterDefinition> defs);
        string pascalKey = StringHelper.ToPascalCase(defaultEntry.Key);

        // Build a set of locale keys whose documents actually contain this entry.
        HashSet<string> localesWithEntry = new(
            locales
                .Where(l => l.Document.Entries.ContainsKey(defaultEntry.Key))
                .Select(l => StringHelper.NormalizeLocale(l.Document.Locale))
        );

        BuildDispatcherSummaryTag(sb, defaultEntry, locales, localesWithEntry);

        if (isParametric) {
            string paramList = BuildParamList(defs);
            string argList = string.Join(", ", defs.Select(d => d.Name));
            sb.AppendLine($"    public string {pascalKey}({paramList}) {{");
            sb.AppendLine($"        return ResolveLocale(_culture) switch {{");
            foreach ((ArbDocument doc, string _) in locales) {
                string key = StringHelper.NormalizeLocale(doc.Locale);
                string arm = ResolveEntryArm(key, localesWithEntry, localeToClass, isParametric: true, pascalKey, argList);
                sb.AppendLine($"            \"{StringHelper.JsonString(key)}\" => {arm},");
            }
            sb.AppendLine($"            _ => throw new System.NotSupportedException(");
            sb.AppendLine($"                $\"No localization found for '{{_culture.Name}}'. Available: {availableLocales}\")");
            sb.AppendLine($"        }};");
            sb.AppendLine($"    }}");
        }
        else {
            sb.AppendLine($"    public string {pascalKey} => ResolveLocale(_culture) switch {{");
            foreach ((ArbDocument doc, string _) in locales) {
                string key = StringHelper.NormalizeLocale(doc.Locale);
                string arm = ResolveEntryArm(key, localesWithEntry, localeToClass, isParametric: false, pascalKey, argList: null);
                sb.AppendLine($"        \"{StringHelper.JsonString(key)}\" => {arm},");
            }
            sb.AppendLine($"        _ => throw new System.NotSupportedException(");
            sb.AppendLine($"            $\"No localization found for '{{_culture.Name}}'. Available: {availableLocales}\")");
            sb.AppendLine($"    }};");
        }
    }

    private static void BuildDispatcherSummaryTag(
        StringBuilder sb,
        ArbEntry defaultEntry,
        IReadOnlyList<(ArbDocument Document, string ClassName)> locales,
        HashSet<string> localesWithEntry
    ) {

        string? description = defaultEntry.Metadata?.Description;

        sb.AppendLine($"    /// <summary>");
        if (!string.IsNullOrWhiteSpace(description)) {
            sb.AppendLine($"    /// {description}");
        }
        sb.AppendLine($"    /// <list type=\"table\">");
        sb.AppendLine($"    /// <listheader><term>Locale</term><description>Value</description></listheader>");

        foreach ((ArbDocument doc, string _) in locales) {
            string normalizedKey = StringHelper.NormalizeLocale(doc.Locale);
            string localeLabel = doc.Locale ?? normalizedKey;

            if (localesWithEntry.Contains(normalizedKey)) {
                // Locale has the entry directly
                ArbEntry localeEntry = doc.Entries[defaultEntry.Key];
                string rendered = StringHelper.XmlEscape(RenderEntryValueForDoc(localeEntry));
                sb.AppendLine($"    /// <item><term>{localeLabel}</term><description>{rendered}</description></item>");
            }
            else {
                // Resolve the fallback chain to describe what happens
                string? fallback = ResolveFallbackLocale(normalizedKey, localesWithEntry);
                if (fallback != null) {
                    sb.AppendLine($"    /// <item><term>{localeLabel}</term><description>[fallback to {fallback}]</description></item>");
                }
                else {
                    sb.AppendLine($"    /// <item><term>{localeLabel}</term><description>[MISSING]</description></item>");
                }
            }
        }

        sb.AppendLine($"    /// </list>");
        sb.AppendLine($"    /// </summary>");
    }

    /// <summary>
    /// Appends a <c>Localize(EnumType)</c> method to <paramref name="sb"/> inside the
    /// dispatcher class body.  Each arm delegates to the already-generated dispatcher
    /// property for the corresponding ARB key, so locale routing is handled automatically.
    /// </summary>
    private static void AppendEnumLocalizeMethod(
        StringBuilder sb,
        string enumFullName,
        string enumSimpleName,
        IReadOnlyList<string> members
    ) {
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Returns the localized display name for a <see cref=\"{enumFullName}\"/> value.</summary>");
        sb.AppendLine($"    public string Localize({enumFullName} value) {{");
        sb.AppendLine($"        return value switch {{");

        foreach (string member in members) {
            string camelKey = char.ToLowerInvariant(enumSimpleName[0]) + enumSimpleName.Substring(1)
                              + char.ToUpperInvariant(member[0]) + member.Substring(1);
            sb.AppendLine($"            {enumFullName}.{member} => {StringHelper.ToPascalCase(camelKey)},");
        }

        sb.AppendLine($"            _ => value.ToString()");
        sb.AppendLine($"        }};");
        sb.AppendLine($"    }}");
    }

    /// <summary>Walks the parent chain to find the nearest ancestor locale that has the entry. Returns null if none found.</summary>
    private static string? ResolveFallbackLocale(string normalizedLocale, HashSet<string> localesWithEntry) {
        string current = normalizedLocale;
        while (true) {
            int lastSep = current.LastIndexOf('_');
            if (lastSep < 0) return null;
            current = current.Substring(0, lastSep);
            if (localesWithEntry.Contains(current)) {
                return current;
            }
        }
    }

    /// <summary>
    /// Renders an entry's value into a human-readable string for use in XML doc comments.
    /// Plural parameters are expanded from <c>{count, plural, =0{...} other{...}}</c>
    /// into a compact inline notation: <c>{count, 0 - "...", 1 - "...", else "..."}</c>.
    /// Simple parameters and surrounding literal text are left as-is.
    /// </summary>
    private static string RenderEntryValueForDoc(ArbEntry entry) {
        if (!entry.IsParametric(out List<ArbParameterDefinition> defs)) {
            return entry.Value;
        }

        // Check if any def is a pluralization — if not, return the raw value unchanged.
        if (!defs.Exists(d => d is ArbPluralizationParameterDefinition)) {
            return entry.Value;
        }

        StringBuilder sb = new();
        int index = 0;

        while (index < entry.Value.Length) {
            // Handle escape sequences — pass them through verbatim
            if (entry.Value[index] == '\\' && index + 1 < entry.Value.Length) {
                sb.Append(entry.Value[index]);
                sb.Append(entry.Value[index + 1]);
                index += 2;
                continue;
            }

            // Check if a parameter starts here
            if (defs.Find(d => d.StartIndex == index) is { } def) {
                if (def is ArbPluralizationParameterDefinition pluralDef) {
                    // Build compact: {name, 0 - "...", 1 - "...", else "..."}
                    sb.Append('{');
                    sb.Append(pluralDef.Name);
                    foreach (KeyValuePair<int, string> kv in pluralDef.CountableParameters.OrderBy(kv => kv.Key)) {
                        sb.Append(", ");
                        sb.Append(kv.Key);
                        sb.Append(" - \"");
                        sb.Append(kv.Value);
                        sb.Append('"');
                    }
                    sb.Append(", else \"");
                    sb.Append(pluralDef.OtherParameter);
                    sb.Append("\"}");
                }
                else {
                    // Simple parameter — keep as {name}
                    sb.Append('{');
                    sb.Append(def.Name);
                    sb.Append('}');
                }
                index = def.EndIndex;
                continue;
            }

            sb.Append(entry.Value[index]);
            index++;
        }

        return sb.ToString();
    }

    /// <summary>
    /// Resolves the switch-arm expression for a given locale and entry key.
    /// <list type="bullet">
    ///   <item>If the locale's document has the entry, calls the locale class directly.</item>
    ///   <item>If missing and the locale is a sub-culture (e.g. <c>en_US</c>), walks up the
    ///         parent chain (<c>en_US</c> → <c>en</c>) to find the nearest ancestor that has it.</item>
    ///   <item>If no ancestor has the entry (neutral/root locale with no match), emits <c>"&lt;MISSING&gt;"</c>.</item>
    /// </list>
    /// </summary>
    private static string ResolveEntryArm(
        string normalizedLocale,
        HashSet<string> localesWithEntry,
        Dictionary<string, string> localeToClass,
        bool isParametric,
        string pascalKey,
        string? argList
    ) {

        string current = normalizedLocale;
        while (true) {
            if (localesWithEntry.Contains(current) && localeToClass.TryGetValue(current, out string? cls)) {
                return isParametric
                    ? $"{cls}.{pascalKey}({argList})"
                    : $"{cls}.{pascalKey}";
            }

            // Strip the last '_'-separated segment to walk up to the parent culture.
            int lastSep = current.LastIndexOf('_');
            if (lastSep < 0) {
                return "\"<MISSING>\"";
            }

            current = current.Substring(0, lastSep);
        }
    }
}