#if !ARB_GENERATOR
using System.IO;
#endif
using System.Text;

namespace Arb.NET;

/// <summary>
/// Generates C# code from parsed .arb documents
/// </summary>
public class ArbCodeGenerator {
    /// <summary>
    /// Generates a C# class from an ARB document
    /// </summary>
    public string GenerateClass(ArbDocument document, string className, string namespaceName) {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Locale: {document.Locale}");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"public static class {className} {{");

        foreach (var entry in document.Entries.Values) {
            GenerateEntry(sb, entry);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

#if !ARB_GENERATOR
    /// <summary>
    /// Parses an .arb file and writes a generated C# file to <paramref name="outputPath"/>
    /// </summary>
    public void GenerateClassFile(string arbFilePath, string outputPath, string className, string namespaceName) {
        var result = new ArbParser().Parse(arbFilePath);
        if (!result.ValidationResults.IsValid) {
            // TODO
            return;
        }
        var source = GenerateClass(result.Document!, className, namespaceName);
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? ".");
        File.WriteAllText(outputPath, source);
    }
#endif

    private static void GenerateEntry(StringBuilder sb, ArbEntry entry) {
        if (entry.IsParametric(out var defs)) {
            var paramList = BuildParamList(defs);

            sb.AppendLine();
            BuildSummaryTag(sb, entry);
            sb.AppendLine($"    public static string {StringHelper.ToPascalCase(entry.Key)}({paramList}) {{");
            BuildPluralizationDefs(sb, defs);
            sb.AppendLine($"        return {BuildFormattedString(entry, defs)};");
            sb.AppendLine($"    }}");
        }
        else {
            sb.AppendLine();
            BuildSummaryTag(sb, entry);
            sb.AppendLine($"    public static string {StringHelper.ToPascalCase(entry.Key)}\n" +
                          $"        => \"{StringHelper.EscapeString(entry.Value)}\";");
        }
    }

    private static string BuildParamList(List<ArbParameterDefinition> names) {
        return string.Join(", ", names.Select(s => {
            if (s is not ArbPluralizationParameterDefinition) {
                return "object " + s.Name;
            }
            else {
                return "int " + s.Name;
            }
        }));
    }

    private static string BuildFormattedString(ArbEntry entry, List<ArbParameterDefinition> defs) {
        StringBuilder sb = new();
        int index = 0;

        sb.Append('$');
        sb.Append('"');

        while (index < entry.Value.Length) {
            char current = entry.Value[index];
            
            if (current == '\\') {
                // Handle escaped characters
                if (index + 1 < entry.Value.Length) {
                    if (entry.Value[index + 1] == '\\') {
                        // Append the escape char itself
                        sb.Append(current);
                    }
                    sb.Append(entry.Value[index + 1]);
                    index += 2;
                    continue;
                }
            }

            if (defs.Find(f => f.StartIndex == index) is { } def) {
                if (def is not ArbPluralizationParameterDefinition) {
                    sb.Append("\"");
                    sb.Append(" + ");
                    sb.Append(def.Name);
                    sb.Append("?.ToString()");
                    sb.Append(" + ");
                    sb.Append("\"");
                    index = def.EndIndex;
                    continue;
                }
                else {
                    sb.Append("\"");
                    sb.Append(" + ");
                    sb.Append($"@selectedContent_{def.Name}");
                    sb.Append(" + ");
                    sb.Append("\"");
                    index = def.EndIndex;
                    continue;
                }
            }
            
            sb.Append(current);

            index++;
        }
        
        sb.Append('"');
        return sb.ToString();
    }
    
    private static void BuildPluralizationDefs(StringBuilder sb, List<ArbParameterDefinition> defs) {
        foreach (var def in defs) {
            if (def is ArbPluralizationParameterDefinition pluralDef) {
                sb.AppendLine($"        // Pluralization parameter: {pluralDef.Name}");
                sb.AppendLine($"        // Plural forms: {string.Join(", ", pluralDef.CountableParameters)}");
                
                sb.AppendLine($"        var @selectedContent_{pluralDef.Name} = ({pluralDef.Name}) switch {{");
                foreach (var form in pluralDef.CountableParameters) {
                    string escapeString = StringHelper.EscapeString(form.Value);
                    escapeString = escapeString.Replace($"{{{def.Name}}}", $"\" + {def.Name}?.ToString() + \"");
                    sb.AppendLine($"            {form.Key} => \"{escapeString}\",");
                }
                string escapeOtherString = StringHelper.EscapeString(pluralDef.OtherParameter);
                escapeOtherString = escapeOtherString.Replace($"{{{def.Name}}}", $"\" + {def.Name}?.ToString() + \"");
                sb.AppendLine($"            _ => \"{escapeOtherString}\"");
                sb.AppendLine("        };");
            }
        }
    }

    private static void BuildSummaryTag(StringBuilder sb, ArbEntry entry) {
        sb.AppendLine($"    /// <summary>{entry.Metadata?.Description ?? entry.Key}</summary>");
        sb.AppendLine($"    /// <returns>Localized string: {entry.Value}</returns>");
    }
}