// <auto-generated/>
// Locale: en_CS

namespace Arb.NET.Example.Localizations;

public static class AppLocale_en_CS {

    /// <summary>The title of the application</summary>
    /// <returns>My Czech Application</returns>
    public static string AppTitle
        => "My Czech Application";

    /// <summary>Number of items with plural handling</summary>
    /// <returns>{count, 0 - "No items", 1 - "{count} item", else "{count} items"}</returns>
    public static string ItemCount(int count) {
        var @selectedContent_count = (count) switch {
            0 => "No items",
            1 => "" + count.ToString() + " item",
            _ => "" + count.ToString() + " items"
        };
        return $"" + @selectedContent_count + "";
    }

    /// <returns>Count (počet): {count, 0 - "No items", 1 - "{count} item", else "{count} items"} is available.</returns>
    public static string ItemCountWithExtras(int count) {
        var @selectedContent_count = (count) switch {
            0 => "No items",
            1 => "" + count.ToString() + " item",
            _ => "" + count.ToString() + " items"
        };
        return $"Count (počet): " + @selectedContent_count + " is available.";
    }

    /// <returns>Souhlasím s &lt;a href="https://finance.patria.cz/otevrit-ucet/patria-finance/podminky-pouzivani"&gt;podmínkami uživání stránek&lt;/a&gt; finance.patria.cz a potvrzuji, že jsem se seznámil s &lt;a href="https://www.csob.cz/cs/csob/ochrana-osobnich-udaju"&gt;informacemi o zpracování osobních údajů a účelem jejich zpracování&lt;/a&gt;. Potvrzuji, že jsem starší 16 let.</returns>
    public static string LongText
        => "Souhlasím s <a href=\"https://finance.patria.cz/otevrit-ucet/patria-finance/podminky-pouzivani\">podmínkami uživání stránek</a> finance.patria.cz a potvrzuji, že jsem se seznámil s <a href=\"https://www.csob.cz/cs/csob/ochrana-osobnich-udaju\">informacemi o zpracování osobních údajů a účelem jejich zpracování</a>. Potvrzuji, že jsem starší 16 let.";

    /// <returns>This (toto) is a simple parameter: {param}</returns>
    public static string SimpleParam(object param) {
        return $"This (toto) is a simple parameter: " + param?.ToString() + "";
    }

    /// <summary>Welcome message with username placeholder</summary>
    /// <returns>Welcome, {username} - OMG!</returns>
    public static string WelcomeMessage(object username) {
        return $"Welcome, " + username?.ToString() + " - OMG!";
    }
}
