// <auto-generated/>
// Locale: en_US

namespace Arb.NET.Example.Localizations;

public static class AppLocale_en_US {

    /// <returns>My US Application</returns>
    public static string AppTitle
        => "My US Application";

    /// <summary>Number of items with plural handling</summary>
    /// <returns>{count, 0 - "No items", 1 - "{count} item", else "{count} items"}</returns>
    /// <example>0 - "No items", 1 - "1 item", n - "n items"</example>
    public static string ItemCount(int count) {
        var @selectedContent_count = (count) switch {
            0 => "No items",
            1 => "" + count.ToString() + " item",
            _ => "" + count.ToString() + " items"
        };
        return $"" + @selectedContent_count + "";
    }

    /// <returns>Yo, count: {count, 0 - "No items", 1 - "{count} item", else "{count} items"} up for grabz bro!</returns>
    /// <example>0 - "No items", 1 - "1 item", n - "n items"</example>
    public static string ItemCountWithExtras(int count) {
        var @selectedContent_count = (count) switch {
            0 => "No items",
            1 => "" + count.ToString() + " item",
            _ => "" + count.ToString() + " items"
        };
        return $"Yo, count: " + @selectedContent_count + " up for grabz bro!";
    }

    /// <returns>Souhlasím s &lt;a href="https://finance.patria.cz/otevrit-ucet/patria-finance/podminky-pouzivani"&gt;podmínkami uživání stránek&lt;/a&gt; finance.patria.cz a potvrzuji, že jsem se seznámil s &lt;a href="https://www.csob.cz/cs/csob/ochrana-osobnich-udaju"&gt;informacemi o zpracování osobních údajů a účelem jejich zpracování&lt;/a&gt;. Potvrzuji, že jsem starší 16 let.</returns>
    public static string LongText
        => "Souhlasím s <a href=\"https://finance.patria.cz/otevrit-ucet/patria-finance/podminky-pouzivani\">podmínkami uživání stránek</a> finance.patria.cz a potvrzuji, že jsem se seznámil s <a href=\"https://www.csob.cz/cs/csob/ochrana-osobnich-udaju\">informacemi o zpracování osobních údajů a účelem jejich zpracování</a>. Potvrzuji, že jsem starší 16 let.";

    /// <returns>Yo this is a simple parameter: {param}</returns>
    public static string SimpleParam(object param) {
        return $"Yo this is a simple parameter: " + param?.ToString() + "";
    }
}
