// <auto-generated/>
// Locale: en

namespace Arb.NET.Example.Localizations;

public static class AppLocale_en {

    /// <summary>The title of the application</summary>
    /// <returns>My Application</returns>
    public static string AppTitle
        => "My Application";

    /// <summary>Number of items with plural handling</summary>
    /// <returns>{count, 0 - "No items", 1 - "{count} item", else "{count} items"}</returns>
    /// <example>0 - "No items", 1 - "1 item", n - "n items"</example>
    public static string ItemCount(int count) {
        var @selectedContent_count = (count) switch {
            0 => "No items",
            1 => "" + count.ToString() + " item",
            _ => "" + count.ToString() + " items"
        };
        return $"" + @selectedContent_count + "";
    }

    /// <returns>Count: {count, 0 - "No items", 1 - "{count} item", else "{count} items"} are available.</returns>
    /// <example>0 - "No items", 1 - "1 item", n - "n items"</example>
    public static string ItemCountWithExtras(int count) {
        var @selectedContent_count = (count) switch {
            0 => "No items",
            1 => "" + count.ToString() + " item",
            _ => "" + count.ToString() + " items"
        };
        return $"Count: " + @selectedContent_count + " are available.";
    }

    /// <returns>I agree with &lt;a href="https://finance.patria.cz/en/open-an-account/patria-finance/usage-conditions"&gt;terms of use of the site&lt;/a&gt; finance.patria.cz and confirm that I have become acquainted with &lt;a href="https://www.csob.cz/en/csob/protection-of-personal-data"&gt;information on the processing of personal data and the purpose of their processing&lt;/a&gt;. I confirm that I am over 16 years old.</returns>
    public static string LongText
        => "I agree with <a href=\"https://finance.patria.cz/en/open-an-account/patria-finance/usage-conditions\">terms of use of the site</a> finance.patria.cz and confirm that I have become acquainted with <a href=\"https://www.csob.cz/en/csob/protection-of-personal-data\">information on the processing of personal data and the purpose of their processing</a>. I confirm that I am over 16 years old.";

    /// <returns>This is a simple parameter: {param}</returns>
    public static string SimpleParam(object param) {
        return $"This is a simple parameter: " + param?.ToString() + "";
    }

    /// <summary>Welcome message with username placeholder</summary>
    /// <returns>Welcome, {username} - OMG!</returns>
    public static string WelcomeMessage(object username) {
        return $"Welcome, " + username?.ToString() + " - OMG!";
    }
}
