// <auto-generated/>
// Available locales: en, en_CS, en_US, cs
#nullable enable

namespace Arb.NET.Example.Localizations;

public partial class AppLocale : global::Arb.NET.IArbLocale {
    private readonly System.Globalization.CultureInfo _culture;

    public AppLocale(System.Globalization.CultureInfo culture) {
        _culture = culture;
    }

    private static string ResolveLocale(System.Globalization.CultureInfo culture) {
        var name = culture.Name.Replace("-", "_");
        return name switch {
            "en" => "en",
            "en_CS" => "en_CS",
            "en_US" => "en_US",
            "cs" => "cs",
            _ => TryParent(culture)
        };
    }

    private static string TryParent(System.Globalization.CultureInfo culture) {
        if (!culture.IsNeutralCulture) {
            var parent = culture.Parent;
            if (!string.IsNullOrEmpty(parent.Name))
                return ResolveLocale(parent);
        }
        throw new System.NotSupportedException(
            $"No localization found for '{culture.Name}'. Available: en, en_CS, en_US, cs");
    }

    /// <summary>
    /// The title of the application
    /// <list type="table">
    /// <listheader><term>Locale</term><description>Value</description></listheader>
    /// <item><term>en</term><description>My Application</description></item>
    /// <item><term>en_CS</term><description>My Czech Application</description></item>
    /// <item><term>en_US</term><description>My US Application</description></item>
    /// <item><term>cs</term><description>Moje aplikace</description></item>
    /// </list>
    /// </summary>
    public string AppTitle => ResolveLocale(_culture) switch {
        "en" => AppLocale_en.AppTitle,
        "en_CS" => AppLocale_en_CS.AppTitle,
        "en_US" => AppLocale_en_US.AppTitle,
        "cs" => AppLocale_cs.AppTitle,
        _ => throw new System.NotSupportedException(
            $"No localization found for '{_culture.Name}'. Available: en, en_CS, en_US, cs")
    };

    /// <summary>
    /// Number of items with plural handling
    /// <list type="table">
    /// <listheader><term>Locale</term><description>Value</description></listheader>
    /// <item><term>en</term><description>{count, 0 - "No items", 1 - "{count} item", else "{count} items"}</description></item>
    /// <item><term>en_CS</term><description>{count, 0 - "No items", 1 - "{count} item", else "{count} items"}</description></item>
    /// <item><term>en_US</term><description>{count, 0 - "No items", 1 - "{count} item", else "{count} items"}</description></item>
    /// <item><term>cs</term><description>{count, 0 - "Žádné položky", 1 - "{count} položka", 2 - "Dvě položky", 3 - "Tři položky", 4 - "Čtyři položky", else "{count} položek"}</description></item>
    /// </list>
    /// </summary>
    /// <example>0 - "No items", 1 - "1 item", n - "n items"</example>
    public string ItemCount(int count) {
        return ResolveLocale(_culture) switch {
            "en" => AppLocale_en.ItemCount(count),
            "en_CS" => AppLocale_en_CS.ItemCount(count),
            "en_US" => AppLocale_en_US.ItemCount(count),
            "cs" => AppLocale_cs.ItemCount(count),
            _ => throw new System.NotSupportedException(
                $"No localization found for '{_culture.Name}'. Available: en, en_CS, en_US, cs")
        };
    }

    /// <summary>
    /// <list type="table">
    /// <listheader><term>Locale</term><description>Value</description></listheader>
    /// <item><term>en</term><description>Count: {count, 0 - "No items", 1 - "{count} item", else "{count} items"} are available.</description></item>
    /// <item><term>en_CS</term><description>Count (počet): {count, 0 - "No items", 1 - "{count} item", else "{count} items"} is available.</description></item>
    /// <item><term>en_US</term><description>Yo, count: {count, 0 - "No items", 1 - "{count} item", else "{count} items"} up for grabz bro!</description></item>
    /// <item><term>cs</term><description>Celkem: {count, 0 - "Žádné položky", 1 - "{count} položka", 2 - "Dvě položky", 3 - "Tři položky", 4 - "Čtyři položky", else "{count} položek"} k dispozici.</description></item>
    /// </list>
    /// </summary>
    /// <example>0 - "No items", 1 - "1 item", n - "n items"</example>
    public string ItemCountWithExtras(int count) {
        return ResolveLocale(_culture) switch {
            "en" => AppLocale_en.ItemCountWithExtras(count),
            "en_CS" => AppLocale_en_CS.ItemCountWithExtras(count),
            "en_US" => AppLocale_en_US.ItemCountWithExtras(count),
            "cs" => AppLocale_cs.ItemCountWithExtras(count),
            _ => throw new System.NotSupportedException(
                $"No localization found for '{_culture.Name}'. Available: en, en_CS, en_US, cs")
        };
    }

    /// <summary>
    /// <list type="table">
    /// <listheader><term>Locale</term><description>Value</description></listheader>
    /// <item><term>en</term><description>I agree with &lt;a href="https://finance.patria.cz/en/open-an-account/patria-finance/usage-conditions"&gt;terms of use of the site&lt;/a&gt; finance.patria.cz and confirm that I have become acquainted with &lt;a href="https://www.csob.cz/en/csob/protection-of-personal-data"&gt;information on the processing of personal data and the purpose of their processing&lt;/a&gt;. I confirm that I am over 16 years old.</description></item>
    /// <item><term>en_CS</term><description>Souhlasím s &lt;a href="https://finance.patria.cz/otevrit-ucet/patria-finance/podminky-pouzivani"&gt;podmínkami uživání stránek&lt;/a&gt; finance.patria.cz a potvrzuji, že jsem se seznámil s &lt;a href="https://www.csob.cz/cs/csob/ochrana-osobnich-udaju"&gt;informacemi o zpracování osobních údajů a účelem jejich zpracování&lt;/a&gt;. Potvrzuji, že jsem starší 16 let.</description></item>
    /// <item><term>en_US</term><description>Souhlasím s &lt;a href="https://finance.patria.cz/otevrit-ucet/patria-finance/podminky-pouzivani"&gt;podmínkami uživání stránek&lt;/a&gt; finance.patria.cz a potvrzuji, že jsem se seznámil s &lt;a href="https://www.csob.cz/cs/csob/ochrana-osobnich-udaju"&gt;informacemi o zpracování osobních údajů a účelem jejich zpracování&lt;/a&gt;. Potvrzuji, že jsem starší 16 let.</description></item>
    /// <item><term>cs</term><description>Souhlasím s &lt;a href="https://finance.patria.cz/otevrit-ucet/patria-finance/podminky-pouzivani"&gt;podmínkami uživání stránek&lt;/a&gt; finance.patria.cz a potvrzuji, že jsem se seznámil s &lt;a href="https://www.csob.cz/cs/csob/ochrana-osobnich-udaju"&gt;informacemi o zpracování osobních údajů a účelem jejich zpracování&lt;/a&gt;. Potvrzuji, že jsem starší 16 let.</description></item>
    /// </list>
    /// </summary>
    public string LongText => ResolveLocale(_culture) switch {
        "en" => AppLocale_en.LongText,
        "en_CS" => AppLocale_en_CS.LongText,
        "en_US" => AppLocale_en_US.LongText,
        "cs" => AppLocale_cs.LongText,
        _ => throw new System.NotSupportedException(
            $"No localization found for '{_culture.Name}'. Available: en, en_CS, en_US, cs")
    };

    /// <summary>
    /// <list type="table">
    /// <listheader><term>Locale</term><description>Value</description></listheader>
    /// <item><term>en</term><description>This is a simple parameter: {param}</description></item>
    /// <item><term>en_CS</term><description>This (toto) is a simple parameter: {param}</description></item>
    /// <item><term>en_US</term><description>Yo this is a simple parameter: {param}</description></item>
    /// <item><term>cs</term><description>Toto je jednoduchý parametr: {param}</description></item>
    /// </list>
    /// </summary>
    public string SimpleParam(object param) {
        return ResolveLocale(_culture) switch {
            "en" => AppLocale_en.SimpleParam(param),
            "en_CS" => AppLocale_en_CS.SimpleParam(param),
            "en_US" => AppLocale_en_US.SimpleParam(param),
            "cs" => AppLocale_cs.SimpleParam(param),
            _ => throw new System.NotSupportedException(
                $"No localization found for '{_culture.Name}'. Available: en, en_CS, en_US, cs")
        };
    }

    /// <summary>
    /// Welcome message with username placeholder
    /// <list type="table">
    /// <listheader><term>Locale</term><description>Value</description></listheader>
    /// <item><term>en</term><description>Welcome, {username} - OMG!</description></item>
    /// <item><term>en_CS</term><description>Welcome, {username} - OMG!</description></item>
    /// <item><term>en_US</term><description>[fallback to en]</description></item>
    /// <item><term>cs</term><description>Ahoj, {username} - OMG!</description></item>
    /// </list>
    /// </summary>
    public string WelcomeMessage(object username) {
        return ResolveLocale(_culture) switch {
            "en" => AppLocale_en.WelcomeMessage(username),
            "en_CS" => AppLocale_en_CS.WelcomeMessage(username),
            "en_US" => AppLocale_en.WelcomeMessage(username),
            "cs" => AppLocale_cs.WelcomeMessage(username),
            _ => throw new System.NotSupportedException(
                $"No localization found for '{_culture.Name}'. Available: en, en_CS, en_US, cs")
        };
    }

    /// <summary>Returns the localized string for the given raw ARB key, or null if not found.</summary>
    public string? this[string? key] => key switch {
        "appTitle" => AppTitle,
        "AppTitle" => AppTitle,
        "longText" => LongText,
        "LongText" => LongText,
        _ => null
    };
}
