// <auto-generated/>
// Locale: cs

namespace Arb.NET.Example.Localizations;

public static class AppLocale_cs {

    /// <summary>Moje lokalizovaná stringa :D - Popis</summary>
    /// <returns>Moje aplikace</returns>
    public static string AppTitle
        => "Moje aplikace";

    /// <summary>Počet položek s podporou plurálu</summary>
    /// <returns>{count, 0 - "Žádné položky", 1 - "{count} položka", 2 - "Dvě položky", 3 - "Tři položky", 4 - "Čtyři položky", else "{count} položek"}</returns>
    /// <example>0 - "Žádné položky", 1 - "1 položka", 2 - "Dvě položky", 3 - "Tři položky", 4 - "Čtyři položky", n - "n položek"</example>
    public static string ItemCount(int count) {
        var @selectedContent_count = (count) switch {
            0 => "Žádné položky",
            1 => "" + count.ToString() + " položka",
            2 => "Dvě položky",
            3 => "Tři položky",
            4 => "Čtyři položky",
            _ => "" + count.ToString() + " položek"
        };
        return "" + @selectedContent_count + "";
    }

    /// <returns>Celkem: {count, 0 - "Žádné položky", 1 - "{count} položka", 2 - "Dvě položky", 3 - "Tři položky", 4 - "Čtyři položky", else "{count} položek"} k dispozici.</returns>
    /// <example>0 - "Žádné položky", 1 - "1 položka", 2 - "Dvě položky", 3 - "Tři položky", 4 - "Čtyři položky", n - "n položek"</example>
    public static string ItemCountWithExtras(int count) {
        var @selectedContent_count = (count) switch {
            0 => "Žádné položky",
            1 => "" + count.ToString() + " položka",
            2 => "Dvě položky",
            3 => "Tři položky",
            4 => "Čtyři položky",
            _ => "" + count.ToString() + " položek"
        };
        return "Celkem: " + @selectedContent_count + " k dispozici.";
    }

    /// <returns>Souhlasím s &lt;a href="https://finance.patria.cz/otevrit-ucet/patria-finance/podminky-pouzivani"&gt;podmínkami uživání stránek&lt;/a&gt; finance.patria.cz a potvrzuji, že jsem se seznámil s &lt;a href="https://www.csob.cz/cs/csob/ochrana-osobnich-udaju"&gt;informacemi o zpracování osobních údajů a účelem jejich zpracování&lt;/a&gt;. Potvrzuji, že jsem starší 16 let.</returns>
    public static string LongText
        => "Souhlasím s <a href=\"https://finance.patria.cz/otevrit-ucet/patria-finance/podminky-pouzivani\">podmínkami uživání stránek</a> finance.patria.cz a potvrzuji, že jsem se seznámil s <a href=\"https://www.csob.cz/cs/csob/ochrana-osobnich-udaju\">informacemi o zpracování osobních údajů a účelem jejich zpracování</a>. Potvrzuji, že jsem starší 16 let.";

    /// <returns>Toto je jednoduchý parametr: {param}</returns>
    public static string SimpleParam(object param) {
        return "Toto je jednoduchý parametr: " + param?.ToString() + "";
    }

    /// <summary>Uvítací zpráva s placeholderem pro uživatelské jméno</summary>
    /// <returns>Ahoj, {username} - OMG!</returns>
    public static string WelcomeMessage(object username) {
        return "Ahoj, " + username?.ToString() + " - OMG!";
    }
}
